GARAGE = [
    {
        "number": "001",
        "year": "1999",
        "make": "NISSAN",
        "model": "SKYLINE GT-R",
        "hero_line_1": "'99 NISSAN",
        "hero_prefix": "SKYLINE GT-",
        "hero_accent": "R",
        "hero_accent_x": 68,
        "hero_accent_color": "red",
        "rear_asset": "r34-hero-transparent.png",
        "front_asset": "r34-front-transparent.png",
        "engine_code": "RB26DETT",
        "engine_size": "2.6L I6",
        "engine_type": "TWIN TURBO",
        "zero_to_sixty": "5.1 SEC",
        "horsepower": "276 HP",
        "top_speed": "112 MPH",
    },
    {
        "number": "002",
        "year": "2024",
        "make": "VOLKSWAGEN",
        "model": "GOLF R",
        "hero_line_1": "'24 VW",
        "hero_prefix": "GOLF ",
        "hero_accent": "R",
        "hero_accent_x": 32,
        "hero_accent_color": "blue",
        "rear_asset": "golf-r-2024-rear-gdn-final.png",
        "front_asset": "golf-r-2024-front-gdn-final.png",
        "engine_code": "EA888 EVO4",
        "engine_size": "2.0L I4",
        "engine_type": "TURBO",
        "zero_to_sixty": "4.1 SEC",
        "horsepower": "315 HP",
        "top_speed": "155 MPH",
    },
    {
        "number": "003",
        "year": "1987",
        "make": "FERRARI",
        "model": "F40",
        "hero_line_1": "87 FERRARI",
        "hero_prefix": "F",
        "hero_accent": "40",
        "hero_accent_x": 8,
        "hero_accent_color": "red",
        "rear_asset": "f40-1987-rear-transparent.png",
        "front_asset": "f40-1987-front-transparent.png",
        "engine_code": "F120A",
        "engine_size": "2.9L V8",
        "engine_type": "TWIN TURBO",
        "zero_to_sixty": "3.8 SEC",
        "horsepower": "478 HP",
        "top_speed": "201 MPH",
    },
    {
        "number": "004",
        "year": "2005",
        "make": "FORD",
        "model": "GT",
        "hero_line_1": "05 FORD",
        "hero_prefix": "G",
        "hero_accent": "T",
        "hero_accent_x": 8,
        "hero_accent_color": "blue",
        "rear_asset": "fordgt-2005-rear-final.png",
        "front_asset": "fordgt-2005-front-final.png",
        "engine_code": "DOHC V8",
        "engine_size": "5.4L V8",
        "engine_type": "SUPERCHARGED",
        "zero_to_sixty": "3.6 SEC",
        "horsepower": "550 HP",
        "top_speed": "205 MPH",
    },
    {
        "number": "005",
        "year": "1994",
        "make": "TOYOTA",
        "model": "SUPRA TURBO",
        "hero_line_1": "94 TOYOTA",
        "hero_prefix": "SUPR",
        "hero_accent": "A",
        "hero_accent_x": 26,
        "hero_accent_color": "orange",
        "rear_asset": "supra-1994-rear-final.png",
        "front_asset": "supra-1994-front-final.png",
        "engine_code": "2JZ-GTE",
        "engine_size": "3.0L I6",
        "engine_type": "TWIN TURBO",
        "zero_to_sixty": "4.6 SEC",
        "horsepower": "320 HP",
        "top_speed": "155 MPH",
    },
    {
        "number": "006",
        "year": "1970",
        "make": "DODGE",
        "model": "CHALLENGER R/T",
        "hero_line_1": "70 DODGE",
        "hero_prefix": "CHALLENGER",
        "hero_accent": "",
        "hero_accent_x": 0,
        "hero_accent_color": "purple",
        "rear_asset": "challenger-1970-rear-final.png",
        "front_asset": "challenger-1970-front-final-v2.png",
        "engine_code": "426 HEMI",
        "engine_size": "7.0L V8",
        "engine_type": "N/A",
        "zero_to_sixty": "5.8 SEC",
        "horsepower": "425 HP",
        "top_speed": "146 MPH",
    },
    {
        "number": "007",
        "year": "1993",
        "make": "MAZDA",
        "model": "RX-7 FD",
        "hero_line_1": "93 MAZDA",
        "hero_prefix": "RX-7 FD",
        "hero_accent": "",
        "hero_accent_x": 0,
        "hero_accent_color": "white",
        "rear_asset": "rx7-1993-rear-final.png",
        "front_asset": "rx7-1993-front-final.png",
        "engine_code": "13B-REW",
        "engine_size": "1.3L ROTARY",
        "engine_type": "TWIN TURBO",
        "zero_to_sixty": "5.0 SEC",
        "horsepower": "255 HP",
        "top_speed": "157 MPH",
    },
    {
        "number": "008",
        "year": "1995",
        "make": "PORSCHE",
        "model": "911 TURBO",
        "hero_line_1": "95 PORSCHE",
        "hero_prefix": "911 TURBO",
        "hero_accent": "",
        "hero_accent_x": 0,
        "hero_accent_color": "white",
        "rear_asset": "porsche-993-1995-rear-gdn-v2.png",
        "front_asset": "porsche-993-1995-front-gdn-v2.png",
        "engine_code": "M64/60",
        "engine_size": "3.6L FLAT-6",
        "engine_type": "TWIN TURBO",
        "zero_to_sixty": "3.7 SEC",
        "horsepower": "400 HP",
        "top_speed": "176 MPH",
    },
    {
        "number": "009",
        "year": "1967",
        "make": "SHELBY",
        "model": "GT500",
        "hero_line_1": "67 SHELBY",
        "hero_prefix": "GT500",
        "hero_accent": "",
        "hero_accent_x": 0,
        "hero_accent_color": "white",
        "rear_asset": "gt500-1967-rear-gdn-final-v3.png",
        "front_asset": "gt500-1967-front-gdn-final-v3.png",
        "engine_code": "428 V8",
        "engine_size": "7.0L V8",
        "engine_type": "N/A",
        "zero_to_sixty": "6.5 SEC",
        "horsepower": "355 HP",
        "top_speed": "128 MPH",
    },
    {
        "number": "010",
        "year": "1988",
        "make": "LAMBORGHINI",
        "model": "COUNTACH 5000 QV",
        "hero_line_1": "88 LAMBO",
        "hero_prefix": "COUNTACH",
        "hero_accent": "",
        "hero_accent_x": 0,
        "hero_accent_color": "yellow",
        "rear_asset": "countach-1988-rear-gdn-final.png",
        "front_asset": "countach-1988-front-gdn-final.png",
        "engine_code": "V12",
        "engine_size": "5.2L V12",
        "engine_type": "N/A",
        "zero_to_sixty": "4.8 SEC",
        "horsepower": "449 HP",
        "top_speed": "183 MPH",
    },
    {
        "number": "011",
        "year": "1963",
        "make": "CHEVROLET",
        "model": "CORVETTE STING RAY",
        "hero_line_1": "63 CHEVY",
        "hero_prefix": "STING RAY",
        "hero_accent": "",
        "hero_accent_x": 0,
        "hero_accent_color": "white",
        "rear_asset": "corvette-1963-rear-gdn-final.png",
        "front_asset": "corvette-1963-front-gdn-final.png",
        "engine_code": "327 V8",
        "engine_size": "5.4L V8",
        "engine_type": "N/A",
        "zero_to_sixty": "6.0 SEC",
        "horsepower": "300 HP",
        "top_speed": "118 MPH",
    },
    {
        "number": "012",
        "year": "2001",
        "make": "BMW",
        "model": "M3",
        "hero_line_1": "01 BMW",
        "hero_prefix": "E46 M3",
        "hero_accent": "",
        "hero_accent_x": 0,
        "hero_accent_color": "blue",
        "rear_asset": "bmw-e46-m3-rear-gdn-final.png",
        "front_asset": "bmw-e46-m3-front-gdn-final.png",
        "engine_code": "S54B32",
        "engine_size": "3.2L I6",
        "engine_type": "N/A",
        "zero_to_sixty": "4.7 SEC",
        "horsepower": "333 HP",
        "top_speed": "155 MPH",
    },
    {
        "number": "013",
        "year": "2001",
        "make": "DAEWOO",
        "model": "LANOS",
        "hero_line_1": "01 DAEWOO",
        "hero_prefix": "LANOS",
        "hero_accent": "",
        "hero_accent_x": 0,
        "hero_accent_color": "white",
        "rear_asset": "daewoo-lanos-2001-rear-gdn-final.png",
        "front_asset": "daewoo-lanos-2001-front-gdn-final.png",
        "engine_code": "DOHC 16V",
        "engine_size": "1.6L I4",
        "engine_type": "N/A",
        "zero_to_sixty": "11.0 SEC",
        "horsepower": "105 HP",
        "top_speed": "114 MPH",
    },
    {
        "number": "014",
        "year": "1996",
        "make": "DODGE",
        "model": "VIPER GTS",
        "hero_line_1": "96 DODGE",
        "hero_prefix": "VIPER GTS",
        "hero_accent": "",
        "hero_accent_x": 0,
        "hero_accent_color": "blue",
        "rear_asset": "viper-gts-1996-rear-gdn-final.png",
        "front_asset": "viper-gts-1996-front-gdn-final.png",
        "engine_code": "V10",
        "engine_size": "8.0L V10",
        "engine_type": "N/A",
        "zero_to_sixty": "4.0 SEC",
        "horsepower": "450 HP",
        "top_speed": "177 MPH",
    },
    {
        "number": "015",
        "year": "2004",
        "make": "SUBARU",
        "model": "IMPREZA WRX STI",
        "hero_line_1": "04 SUBARU",
        "hero_prefix": "WRX ",
        "hero_accent": "STI",
        "hero_accent_x": 26,
        "hero_accent_color": "red",
        "rear_asset": "subaru-wrx-sti-2004-rear-gdn-final.png",
        "front_asset": "subaru-wrx-sti-2004-front-gdn-final.png",
        "engine_code": "EJ257",
        "engine_size": "2.5L FLAT-4",
        "engine_type": "TURBO",
        "zero_to_sixty": "4.6 SEC",
        "horsepower": "300 HP",
        "top_speed": "145 MPH",
    },
    {
        "number": "016",
        "year": "2020",
        "make": "AUDI",
        "model": "R8 V10 PERFORMANCE",
        "hero_line_1": "20 AUDI",
        "hero_prefix": "R8 V10",
        "hero_accent": "",
        "hero_accent_x": 0,
        "hero_accent_color": "red",
        "rear_asset": "audi-r8-v10-2020-rear-gdn-final.png",
        "front_asset": "audi-r8-v10-2020-front-gdn-final.png",
        "engine_code": "5.2 FSI",
        "engine_size": "5.2L V10",
        "engine_type": "N/A",
        "zero_to_sixty": "3.2 SEC",
        "horsepower": "602 HP",
        "top_speed": "205 MPH",
    },
    {
        "number": "017",
        "year": "1991",
        "make": "ACURA",
        "model": "NSX",
        "hero_line_1": "91 ACURA",
        "hero_prefix": "NSX",
        "hero_accent": "",
        "hero_accent_x": 0,
        "hero_accent_color": "red",
        "rear_asset": "acura-nsx-1991-rear-gdn-final.png",
        "front_asset": "acura-nsx-1991-front-gdn-final.png",
        "engine_code": "C30A",
        "engine_size": "3.0L V6",
        "engine_type": "VTEC",
        "zero_to_sixty": "5.2 SEC",
        "horsepower": "270 HP",
        "top_speed": "163 MPH",
    },
    {
        "number": "018",
        "year": "2005",
        "make": "MERCEDES-BENZ",
        "model": "SLR MCLAREN",
        "hero_line_1": "05 MERCEDES",
        "hero_prefix": "SLR MCLAREN",
        "hero_accent": "",
        "hero_accent_x": 0,
        "hero_accent_color": "white",
        "rear_asset": "mercedes-slr-mclaren-2005-rear-gdn-final.png",
        "front_asset": "mercedes-slr-mclaren-2005-front-gdn-final.png",
        "engine_code": "M155",
        "engine_size": "5.4L V8",
        "engine_type": "SUPERCHARGED",
        "zero_to_sixty": "3.6 SEC",
        "horsepower": "617 HP",
        "top_speed": "207 MPH",
    },
    {
        "number": "019",
        "year": "1957",
        "make": "CHEVROLET",
        "model": "BEL AIR",
        "hero_line_1": "57 CHEVY",
        "hero_prefix": "BEL AIR",
        "hero_accent": "",
        "hero_accent_x": 0,
        "hero_accent_color": "cyan",
        "rear_asset": "chevy-bel-air-1957-rear-gdn-final.png",
        "front_asset": "chevy-bel-air-1957-front-gdn-final.png",
        "engine_code": "283 V8",
        "engine_size": "4.6L V8",
        "engine_type": "DUAL QUAD",
        "zero_to_sixty": "9.9 SEC",
        "horsepower": "270 HP",
        "top_speed": "108 MPH",
    },
    {
        "number": "020",
        "year": "2012",
        "make": "LEXUS",
        "model": "LFA NURBURGRING",
        "hero_line_1": "12 LEXUS",
        "hero_prefix": "LFA NURB",
        "hero_accent": "",
        "hero_accent_x": 0,
        "hero_accent_color": "orange",
        "rear_asset": "lexus-lfa-nurburgring-2012-orange-rear-gdn-final.png",
        "front_asset": "lexus-lfa-nurburgring-2012-orange-front-gdn-final.png",
        "engine_code": "1LR-GUE",
        "engine_size": "4.8L V10",
        "engine_type": "N/A",
        "zero_to_sixty": "3.6 SEC",
        "horsepower": "562 HP",
        "top_speed": "202 MPH",
    },
    {
        "number": "021",
        "year": "1995",
        "make": "MITSUBISHI",
        "model": "ECLIPSE GSX",
        "hero_line_1": "95 MITSU",
        "hero_prefix": "ECLIPSE GS",
        "hero_accent": "X",
        "hero_accent_x": 62,
        "hero_accent_color": "green",
        "rear_asset": "eclipse-1995-gsx-rear-gdn-final.png",
        "front_asset": "eclipse-1995-gsx-front-gdn-final.png",
        "engine_code": "4G63T",
        "engine_size": "2.0L I4",
        "engine_type": "TURBO",
        "zero_to_sixty": "6.9 SEC",
        "horsepower": "210 HP",
        "top_speed": "130 MPH",
    },
    {
        "number": "022",
        "year": "1959",
        "make": "CADILLAC",
        "model": "ELDORADO BIARRITZ",
        "hero_line_1": "59 CADILLAC",
        "hero_prefix": "ELDORADO",
        "hero_accent": "",
        "hero_accent_x": 0,
        "hero_accent_color": "pink",
        "rear_asset": "cadillac-eldorado-1959-rear-gdn-final.png",
        "front_asset": "cadillac-eldorado-1959-front-gdn-final.png",
        "engine_code": "390 V8",
        "engine_size": "6.4L V8",
        "engine_type": "TRI-POWER",
        "zero_to_sixty": "10.3 SEC",
        "horsepower": "345 HP",
        "top_speed": "120 MPH",
    },
    {
        "number": "023",
        "year": "1969",
        "make": "CHEVROLET",
        "model": "CAMARO Z/28",
        "hero_line_1": "69 CHEVY",
        "hero_prefix": "CAMARO Z/28",
        "hero_accent": "",
        "hero_accent_x": 0,
        "hero_accent_color": "green",
        "rear_asset": "camaro-z28-1969-rallye-green-rear-gdn-final.png",
        "front_asset": "camaro-z28-1969-rallye-green-front-gdn-final.png",
        "engine_code": "DZ 302",
        "engine_size": "5.0L V8",
        "engine_type": "N/A",
        "zero_to_sixty": "7.4 SEC",
        "horsepower": "290 HP",
        "top_speed": "133 MPH",
    },
    {
        "number": "024",
        "year": "1981",
        "make": "DELOREAN",
        "model": "DMC-12",
        "hero_line_1": "81 DELOREAN",
        "hero_prefix": "DMC-12",
        "hero_accent": "",
        "hero_accent_x": 0,
        "hero_accent_color": "white",
        "rear_asset": "delorean-dmc12-1981-rear-gdn-final.png",
        "front_asset": "delorean-dmc12-1981-front-gdn-final.png",
        "engine_code": "PRV V6",
        "engine_size": "2.85L V6",
        "engine_type": "N/A",
        "zero_to_sixty": "9.5 SEC",
        "horsepower": "130 HP",
        "top_speed": "117 MPH",
    },
    {
        "number": "025",
        "year": "1987",
        "make": "BUICK",
        "model": "GNX",
        "hero_line_1": "87 BUICK",
        "hero_prefix": "",
        "hero_accent": "GN",
        "hero_accent_x": 2,
        "hero_accent_color": "red",
        "hero_suffix": "X",
        "hero_suffix_x": 14,
        "hero_suffix_color": "white",
        "rear_asset": "buick-gnx-1987-rear-gdn-final.png",
        "front_asset": "buick-gnx-1987-front-gdn-final.png",
        "engine_code": "LC2 TURBO",
        "engine_size": "3.8L V6",
        "engine_type": "TURBO",
        "zero_to_sixty": "4.7 SEC",
        "horsepower": "276 HP",
        "top_speed": "124 MPH",
    },
    {
        "number": "026",
        "year": "1994",
        "make": "MCLAREN",
        "model": "F1",
        "hero_line_1": "94 MCLAREN",
        "hero_prefix": "F1",
        "hero_accent": "",
        "hero_accent_x": 0,
        "hero_accent_color": "orange",
        "rear_asset": "mclaren-f1-orange-rear-gdn-final.png",
        "front_asset": "mclaren-f1-orange-front-gdn-final.png",
        "engine_code": "S70/2",
        "engine_size": "6.1L V12",
        "engine_type": "N/A",
        "zero_to_sixty": "3.2 SEC",
        "horsepower": "618 HP",
        "top_speed": "221 MPH",
    },
    {
        "number": "027",
        "year": "2003",
        "make": "FERRARI",
        "model": "ENZO",
        "hero_line_1": "03 FERRARI",
        "hero_prefix": "ENZO",
        "hero_accent": "",
        "hero_accent_x": 0,
        "hero_accent_color": "red",
        "rear_asset": "ferrari-enzo-2003-rear-gdn-final.png",
        "front_asset": "ferrari-enzo-2003-front-gdn-final.png",
        "engine_code": "F140B",
        "engine_size": "6.0L V12",
        "engine_type": "N/A",
        "zero_to_sixty": "3.3 SEC",
        "horsepower": "650 HP",
        "top_speed": "209 MPH",
    },
    {
        "number": "028",
        "year": "2015",
        "make": "DODGE",
        "model": "CHARGER SRT HELLCAT",
        "hero_line_1": "15 DODGE",
        "hero_prefix": "CHARGER",
        "hero_accent": "",
        "hero_accent_x": 0,
        "hero_accent_color": "red",
        "rear_asset": "dodge-charger-srt-hellcat-2015-rear-gdn-final.png",
        "front_asset": "dodge-charger-srt-hellcat-2015-front-gdn-final.png",
        "engine_code": "HELLCAT V8",
        "engine_size": "6.2L V8",
        "engine_type": "SUPERCHARGED",
        "zero_to_sixty": "3.4 SEC",
        "horsepower": "707 HP",
        "top_speed": "204 MPH",
    },
    {
        "number": "029",
        "year": "2005",
        "make": "PORSCHE",
        "model": "CARRERA GT",
        "hero_line_1": "05 PORSCHE",
        "hero_prefix": "CARRERA GT",
        "hero_accent": "",
        "hero_accent_x": 0,
        "hero_accent_color": "white",
        "rear_asset": "porsche-carrera-gt-2005-rear-gdn-final.png",
        "front_asset": "porsche-carrera-gt-2005-front-gdn-final.png",
        "engine_code": "M80/01",
        "engine_size": "5.7L V10",
        "engine_type": "N/A",
        "zero_to_sixty": "3.5 SEC",
        "horsepower": "605 HP",
        "top_speed": "205 MPH",
    },
    {
        "number": "030",
        "year": "1955",
        "make": "MERCEDES-BENZ",
        "model": "300 SL GULLWING",
        "hero_line_1": "55 MERCEDES",
        "hero_prefix": "300 SL",
        "hero_accent": "",
        "hero_accent_x": 0,
        "hero_accent_color": "white",
        "rear_asset": "mercedes-300sl-gullwing-1955-rear-gdn-final.png",
        "front_asset": "mercedes-300sl-gullwing-1955-front-gdn-final.png",
        "engine_code": "M198",
        "engine_size": "3.0L I6",
        "engine_type": "FUEL INJECT",
        "zero_to_sixty": "7.4 SEC",
        "horsepower": "215 HP",
        "top_speed": "140 MPH",
    },
]


ROTATION = [
    17, 3, 24, 8, 29, 12, 1, 21, 6, 26,
    14, 4, 19, 10, 27, 2, 23, 16, 7, 30,
    11, 25, 5, 18, 9, 28, 13, 22, 15, 20,
]


def get_daily_car(ctx):
    slot = ((ctx.now.yday - 1) * 12) + (ctx.now.hour // 2)

    rotation_index = slot % len(ROTATION)
    car_index = ROTATION[rotation_index] - 1

    return GARAGE[car_index]


def main(c, ctx):
    CAR = get_daily_car(ctx)

    c.fill("black")
    c.image(CAR["rear_asset"], 0, 0)

    c.text("DAILY DRIVER", 2, 2, font="5x7", color="red")
    c.text(CAR["hero_line_1"], 2, 11, font="5x7", color="white")
    c.text(CAR["hero_prefix"], 2, 20, font="5x7", color="white")

    c.text(
        CAR["hero_accent"],
        CAR["hero_accent_x"],
        20,
        font="5x7",
        color=CAR["hero_accent_color"],
    )

    if "hero_suffix" in CAR:
        c.text(
            CAR["hero_suffix"],
            CAR["hero_suffix_x"],
            20,
            font="5x7",
            color=CAR["hero_suffix_color"],
        )


def engine_specs(c, ctx):
    CAR = get_daily_car(ctx)

    c.fill("black")
    c.image(CAR["front_asset"], 0, 0)

    c.text("ENGINE", 2, 1, font="5x7", color="red")
    c.text(CAR["engine_code"], 2, 9, font="5x7", color="white")
    c.text(CAR["engine_size"], 2, 17, font="5x7", color="yellow")
    c.text(CAR["engine_type"], 2, 25, font="5x7", color="white")


def performance(c, ctx):
    CAR = get_daily_car(ctx)

    c.fill("black")
    c.text("PERFORMANCE", 2, 1, font="5x7", color="red")

    c.line(4, 27, 4, 20, color="white")
    c.line(4, 20, 7, 15, color="white")
    c.line(7, 15, 12, 11, color="white")
    c.line(12, 11, 18, 10, color="white")
    c.line(18, 10, 24, 12, color="white")
    c.line(24, 12, 28, 16, color="white")
    c.line(28, 16, 31, 21, color="white")
    c.line(31, 21, 31, 27, color="white")

    c.line(7, 23, 10, 22, color="white")
    c.line(10, 16, 13, 17, color="white")
    c.line(18, 11, 18, 14, color="white")
    c.line(25, 16, 22, 18, color="white")
    c.line(30, 23, 27, 23, color="red")

    c.line(18, 24, 26, 16, color="red")
    c.rect(16, 22, 19, 25, fill="red")

    c.text("0-60", 39, 8, font="5x7", color="yellow")
    c.text(CAR["zero_to_sixty"], 70, 8, font="5x7", color="white")

    c.text("HP", 39, 17, font="5x7", color="cyan")
    c.text(CAR["horsepower"], 55, 17, font="5x7", color="white")

    c.text("TOP", 39, 25, font="5x7", color="yellow")
    c.text(CAR["top_speed"], 61, 25, font="5x7", color="white")