export function dashboard(){
  const nonce=crypto.randomUUID();
  return new Response(`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Commute</title><style>
  :root{color-scheme:dark;font-family:system-ui,sans-serif;background:#080e17;color:#eaf3ff}*{box-sizing:border-box}body{max-width:920px;margin:auto;padding:36px 22px}header{display:flex;align-items:center;gap:16px;margin-bottom:30px}.road{font-size:34px}h1{font-size:36px;margin:0;letter-spacing:-1px}.muted{color:#9fb0c9}p{line-height:1.5}form{display:flex;flex-wrap:wrap;gap:12px}input,button,a.button{font:inherit;border:1px solid #34475e;border-radius:12px;padding:13px 18px}input{background:#111e2d;color:white;flex:1}button,a.button{background:#65edb1;color:#092218;font-weight:700;cursor:pointer;text-decoration:none}section{margin-top:25px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(255px,1fr));gap:16px}.card{background:#111c2b;border:1px solid #263950;border-radius:20px;padding:24px}.eyebrow{text-transform:uppercase;letter-spacing:2px;font-size:12px;color:#65edb1}.eta{font-size:64px;font-weight:750;margin:10px 0;letter-spacing:-3px}.eta small{font-size:20px;letter-spacing:0;color:#9fb0c9}.route{font-size:23px;margin:0 0 12px}.times{color:#b6c6dd;line-height:1.9;margin-bottom:22px}.warning{color:#ffd172}.error{color:#ff8895}li{line-height:1.7;margin-bottom:10px}footer{margin-top:32px;color:#91a3bd;font-size:13px}#refresh{background:transparent;color:#b9d9ee}a{color:#77bdff}[hidden]{display:none!important}
  </style></head><body><header><div class="road" aria-hidden="true">🛣️</div><div><h1>Commute</h1><div class="muted">A better start to your drive.</div></div></header>
  <form id="unlock"><label for="key" class="muted">Your private Commute read key</label><input id="key" type="password" autocomplete="off" required minlength="24" aria-label="Read key"><button>Open my commute</button></form><p id="message" role="status" class="muted">Your key stays in this tab’s memory. Close the tab to clear it.</p>
  <main id="content" hidden><p><label for="arrival">Arrive by </label><select id="arrival"><option value="Configured">Configured time</option><option value="08:00">8:00 AM</option><option value="08:15">8:15 AM</option><option value="08:30">8:30 AM</option></select></p><div class="grid"><article class="card"><div class="eyebrow">Direct to work</div><div class="eta"><span id="direct-min">—</span> <small>min</small></div><h2 id="direct-road" class="route"></h2><div class="times" id="direct-times"></div><a class="button" id="direct-waze" target="_blank" rel="noopener noreferrer">Open in Waze ↗</a></article><article class="card"><div id="stop-label" class="eyebrow">With a stop</div><div class="eta"><span id="stop-min">—</span> <small>min</small></div><h2 id="stop-road" class="route"></h2><div class="times" id="stop-times"></div><a class="button" id="stop-waze" target="_blank" rel="noopener noreferrer">Navigate to stop ↗</a></article></div>
  <section><h2>Route options</h2><ul id="alternatives"></ul></section><section><h2>Weather &amp; road conditions</h2><p id="weather"></p><ul id="alerts"></ul><h3>Weather observations along the route</h3><p class="muted">Sampled stations near the route. Visibility is the lowest reported reading, not continuous coverage. Road sensors describe their own location.</p><ul id="route-weather"></ul><p id="coverage" class="muted"></p></section><button id="refresh">Check display data</button><p class="muted">Leave-by times estimate today’s deadline using the current travel time. Waze calculates its own route when opened; it may differ from this display. After your stop, use “Open in Waze” to navigate to work.</p></main>
  <footer>Traffic estimates: TomTom · Weather and warnings: National Weather Service · Ohio road reports: OHGO. Nearby reports can include adjacent or opposite-direction roads. County snow levels require a connected official-source feed.</footer>
  <script nonce="${nonce}">
  const el=id=>document.getElementById(id);let key='',busy=false;
  const set=(id,value)=>{el(id).textContent=value};
  function link(id,value){const a=el(id);a.hidden=!value;if(value){const u=new URL(value);if(u.protocol==='https:'&&u.hostname==='waze.com')a.href=u.href;else a.hidden=true;}}
  function route(prefix,r){set(prefix+'-min',r?r.minutes:'—');set(prefix+'-road',r?'Via '+r.road.label:'Not available');set(prefix+'-times',r?'Arrive '+r.arrival+' · Leave by '+r.leaveBy+' (estimate)'+(r.late?' · Arrives late':''):'Configure a stop to compare this trip.');}
  function showRouteWeather(data){
    const list=el('route-weather');list.replaceChildren();
    const append=text=>{const li=document.createElement('li');li.textContent=text;list.append(li)};
    const fmt=(v,unit)=>Number.isFinite(v)?Math.round(v*100)/100+unit:'not reported';
    const age=at=>Number.isFinite(at)?Math.max(0,Math.floor(Date.now()/1000-at)/60).toFixed(0)+' min old':'age unknown';
    for(const [trip,w] of Object.entries(data||{})){
      if(!w)continue;const name=trip==='stop'?'With stop':'Direct';
      for(const o of w.observations||[])append(name+' · '+o.location+' · NWS '+o.station.split('/').pop()+' · '+fmt(o.temperatureF,'°F')+' · visibility '+fmt(o.visibilityMiles,' mi')+' · '+o.description+' · '+age(o.observedAt));
      for(const site of w.sensors||[]){
        for(const a of site.atmosphere)append(name+' · OHGO '+site.location+' · '+fmt(a.temperatureF,'°F')+' · visibility '+fmt(a.visibilityMiles,' mi')+' · precipitation '+a.description+' · wind '+fmt(a.windMph,' mph')+' · '+age(a.observedAt));
        for(const r of site.surfaces)append(name+' · OHGO '+site.location+' / '+r.name+' · pavement '+fmt(r.temperatureF,'°F')+' · '+r.status+' · subsurface '+fmt(r.subsurfaceF,'°F')+' · '+age(r.observedAt));
      }
      if(!w.observations?.length&&!w.sensors?.length)append(name+': no fresh observations near the route.');
    }
  }
  async function update(){if(!key||busy)return;busy=true;try{const r=await fetch('/status?arriveby='+encodeURIComponent(el('arrival').value),{headers:{Authorization:'Bearer '+key},cache:'no-store'});if(!r.ok)throw Error(r.status===401?'Check your read key.':'Waiting for the commute service.');const d=await r.json();showRouteWeather(d.routeWeather);const trafficMissing=d.stale||d.state!=='ok';el('content').hidden=false;set('message','Traffic checked '+d.checkedTime+' · '+Math.ceil(d.ageSeconds/60)+' min ago');route('direct',trafficMissing?null:d.direct);route('stop',trafficMissing?null:d.stop);if(trafficMissing)set('message','Traffic unavailable. Alerts refer to the last calculated route.');set('stop-label','With '+d.stopName);link('direct-waze',d.navigation?.destination);link('stop-waze',d.stop?d.navigation?.stop:null);el('alternatives').replaceChildren();for(const a of (trafficMissing?[]:[d.direct,...(d.alternatives||[])])){const li=document.createElement('li');li.textContent=a.road.label+' — '+a.minutes+' min';el('alternatives').append(li);}if(d.comparisonPartial){const li=document.createElement('li');li.textContent='Some route comparisons are unavailable.';el('alternatives').append(li);}set('weather',d.weather.description+(d.weather.temperatureF!==null?' · '+d.weather.temperatureF+'°F':'')+' · near your starting location');el('alerts').replaceChildren();const seen=new Set();for(const [trip,items] of Object.entries(d.alerts)){for(const a of items){const k=trip+a.id;if(seen.has(k))continue;seen.add(k);const li=document.createElement('li');li.textContent=(trip==='stop'?'With stop: ':'Direct: ')+a.title+' — '+a.detail+' ('+a.source+', '+a.scope.toLowerCase()+')';li.className=['Extreme','Severe'].includes(a.severity)?'error':'warning';el('alerts').append(li);}}if(!seen.size){const li=document.createElement('li');li.textContent='No alerts reported by available feeds. This is not an all-clear guarantee.';el('alerts').append(li);}const names={weatherAlerts:'Weather alerts',roads:'Road reports',county:'County snow levels'};set('coverage',Object.entries(names).map(([k,n])=>n+': '+(d.sources[k]?.state||'unavailable')+(d.sources[k]?.coverage?' ('+d.sources[k].coverage+')':'')).join(' · '));}catch(e){set('message',e.message);el('content').hidden=true;}finally{busy=false;}}
  el('unlock').addEventListener('submit',e=>{e.preventDefault();key=el('key').value;el('key').value='';update()});el('refresh').addEventListener('click',update);el('arrival').addEventListener('change',update);setInterval(update,60000);
  </script></body></html>`,{headers:{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store','Referrer-Policy':'no-referrer','X-Content-Type-Options':'nosniff','Content-Security-Policy':`default-src 'none'; script-src 'nonce-${nonce}'; style-src 'unsafe-inline'; connect-src 'self'; img-src 'self' data:; base-uri 'none'; form-action 'none'; frame-ancestors 'none'`}});
}
