"""Regenerate the Athlete Tracker player dropdown from ESPN fantasy ownership.

Run it by hand when the list needs refreshing (start of a season, after the
trade deadline, ...):

    python tools/athlete_tracker_players.py            # top 250 per league
    python tools/athlete_tracker_players.py --top 100

It rewrites two generated blocks and nothing else:
  * apps/athlete-tracker/manifest.yaml  - the `player` dropdown choices
  * apps/athlete-tracker/app.star       - PLAYERS, label -> (league, ESPN id)

PLAYERS only ever grows: a player who drops out of the top N leaves the
dropdown but keeps their entry, so panels already set to them keep working.
"""
import argparse
import datetime
import json
import os
import re
import urllib.request

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
APP = os.path.join(ROOT, "apps", "athlete-tracker")

# league -> (ESPN fantasy game, ESPN site path)
LEAGUES = {
    "NFL": ("ffl", "football/nfl"),
    "NBA": ("fba", "basketball/nba"),
    "NHL": ("fhl", "hockey/nhl"),
    "MLB": ("flb", "baseball/mlb"),
}
DEFAULT = "Patrick Mahomes (NFL)"


def get(url, headers=None):
    req = urllib.request.Request(url, headers=dict({"User-Agent": "athlete-tracker"}, **(headers or {})))
    with urllib.request.urlopen(req, timeout=60) as r:
        return json.loads(r.read().decode("utf-8"))


def fantasy_seasons(game, today):
    """Seasons to try, newest first. NBA/NHL seasons are named for the year they end."""
    y = today.year
    if game in ("fba", "fhl"):
        return [y + 1, y] if today.month >= 8 else [y, y - 1]
    if game == "ffl":
        return [y, y - 1] if today.month >= 3 else [y - 1, y - 2]
    return [y, y - 1]


def top_players(game, n, today):
    # ask for extra: team defenses are filtered out below
    filt = {"players": {"limit": n + 50, "filterActive": {"value": True},
                        "sortPercOwned": {"sortPriority": 1, "sortAsc": False}}}
    for season in fantasy_seasons(game, today):
        url = (f"https://lm-api-reads.fantasy.espn.com/apis/v3/games/{game}/seasons/{season}"
               f"/segments/0/leaguedefaults/3?view=kona_player_info")
        try:
            data = get(url, {"x-fantasy-filter": json.dumps(filt)})
        except Exception:
            continue
        players = [p["player"] for p in data.get("players", [])]
        # team defenses are not people
        players = [p for p in players if p.get("id", 0) > 0 and "D/ST" not in p.get("fullName", "")]
        if players:
            return season, players[:n]
    raise SystemExit(f"no fantasy players for {game}")


def team_abbrevs(site):
    data = get(f"https://site.api.espn.com/apis/site/v2/sports/{site}/teams")
    teams = data["sports"][0]["leagues"][0]["teams"]
    return {int(t["team"]["id"]): t["team"]["abbreviation"] for t in teams}


def read_existing():
    src = open(os.path.join(APP, "app.star"), encoding="utf-8").read()
    m = re.search(r"# BEGIN PLAYERS.*?\n(.*?)# END PLAYERS", src, re.S)
    found = {}
    if m:
        for label, lg, pid in re.findall(r'"(.+?)": \("(\w+)", (\d+)\),', m.group(1)):
            found[label] = (lg, int(pid))
    return found


def build(n):
    today = datetime.date.today()
    current = {}
    for league, (game, site) in LEAGUES.items():
        season, players = top_players(game, n, today)
        abbr = team_abbrevs(site)
        names = {}
        for p in players:
            names.setdefault(p["fullName"], []).append(p)
        for name, group in names.items():
            for p in group:
                if len(group) == 1:
                    label = f"{name} ({league})"
                else:
                    label = f"{name} ({league}, {abbr.get(p.get('proTeamId'), 'FA')})"
                current[label] = (league.lower(), p["id"])
        print(f"{league}: {len(players)} players (fantasy season {season})")
    return current


def write(current):
    table = read_existing()
    known_ids = {v for v in table.values()}
    for label, v in current.items():
        if v not in known_ids:
            table[label] = v
        elif label not in table:
            # same player under a new label (e.g. a name collision appeared): keep both
            table[label] = v

    # app.star: the full, append-only lookup table
    path = os.path.join(APP, "app.star")
    src = open(path, encoding="utf-8").read()
    body = "".join(f'    {json.dumps(k)}: ("{lg}", {pid}),\n' for k, (lg, pid) in sorted(table.items()))
    block = ("# BEGIN PLAYERS (generated by tools/athlete_tracker_players.py; do not edit by hand)\n"
             "PLAYERS = {\n" + body + "}\n# END PLAYERS")
    src = re.sub(r"# BEGIN PLAYERS.*?# END PLAYERS", lambda _: block, src, flags=re.S)
    open(path, "w", encoding="utf-8", newline="\n").write(src)

    # manifest.yaml: only the current top N, A-Z
    choices = sorted(current, key=lambda s: s.lower())
    default = DEFAULT if DEFAULT in current else choices[0]
    path = os.path.join(APP, "manifest.yaml")
    man = open(path, encoding="utf-8").read()
    flow = "[" + ", ".join(json.dumps(c) for c in choices) + "]"
    # docs call the list `choices`; the Studio/tooling read `options`. Write both.
    block = ("  # BEGIN PLAYER INPUT (generated by tools/athlete_tracker_players.py)\n"
             "  - key: player\n"
             "    app_input_type: dropdown\n"
             "    type: choice\n"
             "    label: Player\n"
             f"    default: {json.dumps(default)}\n"
             "    help: Pick a player. Page 1 shows their season, page 2 their live game or next-game projection.\n"
             f"    choices: {flow}\n"
             f"    options: {flow}\n"
             "  # END PLAYER INPUT")
    man = re.sub(r"  # BEGIN PLAYER INPUT.*?  # END PLAYER INPUT", lambda _: block, man, flags=re.S)
    open(path, "w", encoding="utf-8", newline="\n").write(man)
    print(f"dropdown: {len(choices)} players; lookup table: {len(table)} players")


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--top", type=int, default=250, help="players per league (default 250)")
    write(build(ap.parse_args().top))
