import assert from 'node:assert/strict';
import {XboxOwner,snapshot} from './worker.mjs';
class Storage{constructor(){this.data=new Map();}async get(k){return this.data.get(k);}async put(k,v){this.data.set(k,v);}async delete(k){this.data.delete(k);}async transaction(fn){return fn(this);}}
const env={PUBLIC_URL:'https://example.invalid',CLIENT_ID:'example',ADMIN_KEY:'a'.repeat(43),READ_KEY:'r'.repeat(43),WRITE_KEY:'w'.repeat(43),HANDOFF_KEY:Buffer.alloc(32,7).toString('base64url')};
const store=new Storage(),owner=new XboxOwner({storage:store},env);
const req=(path,method='GET',body=null,headers={})=>new Request(env.PUBLIC_URL+path,{method,headers,body});
const auth=key=>({Authorization:'Bearer '+key});
assert.equal((await owner.fetch(req('/status'))).status,401);
assert.equal((await owner.fetch(req('/collector/grant','POST','{}',auth(env.READ_KEY)))).status,401);
assert.equal((await owner.fetch(req('/ingest','POST','{}',auth(env.READ_KEY)))).status,401);
assert.equal(store.data.size,0);
assert.equal((await owner.fetch(req('/connect','POST','key='+env.ADMIN_KEY,{Origin:'https://evil.invalid'}))).status,403);
const ticket=(await (await owner.fetch(req('/admin/ticket','POST','{}',auth(env.ADMIN_KEY)))).json()).ticket;
const begin=await owner.fetch(req('/start','POST',new URLSearchParams({ticket}).toString()));
assert.equal(begin.status,303);
assert.equal((await owner.fetch(req('/start','POST',new URLSearchParams({ticket}).toString()))).status,403);
const url=new URL(begin.headers.get('Location')),state=url.searchParams.get('state');
assert.equal(url.origin,'https://login.microsoftonline.com');
assert.equal(url.searchParams.get('scope'),'XboxLive.signin offline_access');
assert.equal(url.searchParams.get('code_challenge_method'),'S256');
assert.equal((await owner.fetch(req('/auth/callback?code=private-code&state='+state))).status,400);
const result=await owner.fetch(req('/auth/callback?code=private-code&state='+state,'GET',null,{Cookie:'xbox_state='+state}));
assert.equal(result.status,303);
assert.equal((await owner.fetch(req('/auth/callback?code=private-code&state='+state,'GET',null,{Cookie:'xbox_state='+state}))).status,400);
assert(!JSON.stringify([...store.data.values()]).includes('private-code'));
const grant=(await (await owner.fetch(req('/collector/grant','POST','{}',auth(env.WRITE_KEY)))).json()).grant;
const key=await crypto.subtle.importKey('raw',Buffer.from(env.HANDOFF_KEY,'base64url'),'AES-GCM',false,['decrypt']);
const decoded=JSON.parse(new TextDecoder().decode(await crypto.subtle.decrypt({name:'AES-GCM',iv:Buffer.from(grant.iv,'base64url')},key,Buffer.from(grant.data,'base64url'))));
assert.equal(decoded.code,'private-code');assert(decoded.verifier.length>=43);
assert.equal((await (await owner.fetch(req('/collector/grant','POST','{}',auth(env.WRITE_KEY)))).json()).grant,null);
const data={schema:1,state:'ready',updated:Math.floor(Date.now()/1000),profile:{gamertag:'PLAYER',token:'secret'},refresh_token:'secret',presence:{}};
assert(!JSON.stringify(snapshot(data)).includes('secret'));
assert.equal(snapshot({...data,friends:{state:'ready',items:[{name:'FRIEND'}]}}).friends.items.length,0);
assert.equal(snapshot({...data,friends:{state:'ready',items:[{name:'FRIEND'}]}},true).friends.items.length,1);
assert.equal((await owner.fetch(req('/ingest','POST',JSON.stringify(data),auth(env.WRITE_KEY)))).status,200);
const read=await (await owner.fetch(req('/status','GET',null,auth(env.READ_KEY)))).json();
assert.equal(read.profile.gamertag,'PLAYER');assert(!JSON.stringify(read).includes('secret'));
assert.throws(()=>snapshot({...data,updated:1}));
assert.equal((await owner.fetch(req('/admin/ticket','POST','{}',auth(env.WRITE_KEY)))).status,401);
console.log('PASS: separate keys, unauthorized boundaries, CSRF, PKCE, cookie binding, one-use state/ticket/grant, encrypted handoff, snapshot allowlist and freshness.');
