# Nutrition at a Glance - one food at a time, and what it actually gives you.
#
# DATA. Curated, 69 foods, per 100 g, raw unless the README says otherwise.
# The table stays per 100 g because that is the basis it was checked on;
# every figure drawn is scaled to one serving from SERVINGS, because 403
# KCAL for cheddar is a 100 g block nobody eats in one go.
# Composition does not change, so this app makes NO network calls at all and
# cannot fail on a feed. The ten minute refresh turns the food over, it does
# not fetch anything.
#
# Seven foods were machine checked against USDA FoodData Central before the
# free key rate limited; the rest are standard reference figures. Each row
# records which it is, and the README says so plainly rather than implying
# the whole table was verified.
#
# Every value was also cross-checked against energy: kcal should be close to
# 4*protein + 9*fat + 4*carb, charging fibre at 2 kcal/g. That caught a real
# error - lentils had been given 30.5 g of fibre, which is the daily
# reference intake, not the content of the food.
#
# THE ART. One sprite per shape, recoloured per food from a five tone
# palette, so a fillet reads as salmon, cod or tuna through its tones alone.
# c.sprite costs one draw op no matter how many pixels it lights, and a page
# may emit 4096, which is why the food is per-pixel art rather than an
# assembly of rectangles.
#
# THE BARS. Length is the share of the reference intake. Colour is the
# food's own, not a verdict: this panel is not qualified to tell anyone that
# fat is bad or that protein is good. The one judgement it does make is
# factual - the bar turns green when a single serving meets the whole
# reference intake.
#
# SCREENS. The design guide asks for live, error, empty and demo. With no
# feed and no key, error and demo cannot occur here. Live is the app; the
# empty screen is kept as a guard in case a group is ever emptied by a later
# edit, and it is written positive rather than as a fault.

INK = "#FFFFFF"
DIM = "#7C8BA1"
FAINT = "#252E3C"
TRACK = "#1A2230"
MET = "#00DC46"

# Reference intakes are per day. Protein is pinned at 100 g rather than the
# usual 50 g reference value, which is what the brief asked for, and the
# README says so where someone might otherwise think it a mistake.

# Palettes, five tones each, in the legend order the artwork uses:
# H highlight, M mid, D dark and outline, A the food's own accent,
# G a secondary accent such as a yolk, a stone or a liquid. One
# shape serves several foods, so the palette is what makes a fillet
# read as salmon, as cod or as tuna.
PALETTES = {
    "almond": ["#E8C49A", "#C08A56", "#6E4A28", "#F0DCC0", "#8A5830"],
    "avocado": ["#D8EC8E", "#306E2C", "#123412", "#BFDD70", "#945E2C"],
    "bacon": ["#EC7460", "#BD4034", "#561A16", "#F9DEC8", "#FFFFFF"],
    "bean": ["#8A7898", "#3A2C46", "#150E1E", "#52405E", "#241A2E"],
    "beef": ["#E0736A", "#B03A38", "#521619", "#F2E3C8", "#FFFFFF"],
    "butter": ["#FFF1A3", "#F6D352", "#805E14", "#FFF6B6", "#E2E7EC"],
    "cheese": ["#FFE27C", "#ECBA38", "#764E0C", "#FFEC98", "#C67626"],
    "chickpea": ["#F0DCA8", "#D4B46A", "#7A6030", "#E8CC8C", "#A07838"],
    "crab": ["#FFA273", "#E2502B", "#761E10", "#FFD0B0", "#FFFFFF"],
    "duck": ["#E8B79A", "#C2795A", "#6E3A28", "#A85F44", "#F2E6CF"],
    "egg": ["#FFFFFF", "#EFE9DC", "#9A7A52", "#C6760F", "#F5B233"],
    "grain": ["#F6E2B5", "#D8BF8D", "#6C5430", "#E5CC9C", "#B29467"],
    "green": ["#8ED45C", "#50A638", "#164418", "#60B53C", "#3A8026"],
    "ham": ["#FFB6B3", "#EA8287", "#8A3944", "#F5E2C0", "#F9F1DC"],
    "lamb": ["#E88A80", "#B84A44", "#581C1C", "#EADFC2", "#F7F0DE"],
    "lentil": ["#F2985C", "#D66E3C", "#662C14", "#E27E46", "#94441C"],
    "liver": ["#B0626A", "#7B3038", "#38121A", "#5E2029", "#C98088"],
    "lobster": ["#FF9E7A", "#D8482E", "#7A2014", "#FFD0B8", "#FFFFFF"],
    "milk": ["#EEF6FC", "#8A9DB0", "#2E3C4C", "#FFFFFF", "#FAFAF2"],
    "mussel": ["#7A6A88", "#46304E", "#1E1226", "#E8A87C", "#EC9EA0"],
    "oil": ["#CAE2B0", "#96B579", "#26401E", "#789C46", "#E2C45A"],
    "oily": ["#C6DAE6", "#809DB2", "#2A3F4F", "#5B7A8F", "#F2C233"],
    "oyster": ["#EDE7D9", "#BBB19D", "#565043", "#8F8676", "#EC9EA0"],
    "peanut": ["#FFFFFF", "#C0C5CF", "#483420", "#C9883C", "#E44436"],
    "pork": ["#FFD8C8", "#F0A88E", "#9A5A44", "#EADFC2", "#F7F0DE"],
    "poultry": ["#FFE9D2", "#F0C9A0", "#9B6E44", "#C08050", "#F2E6CF"],
    "salmon": ["#FFB183", "#F2793C", "#8A3A16", "#C8CDD2", "#FFFFFF"],
    "seed": ["#C8D88A", "#8AA84A", "#46601E", "#E0E8B0", "#5E7A28"],
    "shrimp": ["#FFCCAB", "#F7885A", "#8A3A22", "#FFE2CE", "#FFFFFF"],
    "squid": ["#F7E6EA", "#DCB2BA", "#6E4650", "#C08E98", "#FFFFFF"],
    "sweet": ["#F2A26A", "#D87442", "#663018", "#E2834C", "#9E4E26"],
    "tempeh": ["#E8D8B0", "#C0A870", "#6E5C34", "#D4BC88", "#9C845C"],
    "tofu": ["#FFFFF6", "#E8E4D0", "#74705C", "#F8F5E5", "#C6C1AD"],
    "tuna": ["#E06868", "#A82E3E", "#52141E", "#F2E3C8", "#FFFFFF"],
    "venison": ["#C07868", "#8E3C30", "#4A1C14", "#F2E3C8", "#FFFFFF"],
    "walnut": ["#D8B48A", "#A8763E", "#5E3C1C", "#C89A6A", "#6E4520"],
    "whey": ["#CED8E4", "#748192", "#28303C", "#F0D8B2", "#FFFFFF"],
    "white": ["#FFFFFF", "#E6E9EE", "#7E848E", "#D2D8E0", "#F4F7FB"],
    "yogurt": ["#FFFDF7", "#E4E0D6", "#5C5850", "#FFFFFF", "#E8487A"],
}

# Reference intakes. These are the EU Nutrient Reference Values,
# except protein, which is set to 100 g rather than the usual 50 g.
TARGETS = {
    "PROTEIN": 100.0,
    "FAT": 70.0,
    "CARB": 260.0,
    "FIBRE": 30.0,
    "B12": 2.4,
    "B6": 1.4,
    "ZINC": 10.0,
    "IRON": 14.0,
    "SELENIUM": 55.0,
    "MAGNESIUM": 375.0,
}

# name, group, shape, palette, kcal, protein g, fat g, carb g,
# fibre g, B12 ug, B6 mg, zinc mg, iron mg, selenium ug,
# magnesium mg, source. Per 100 g, raw unless the README says
# otherwise. Source is USDA where that value was machine checked
# against FoodData Central, REF where it is a standard reference
# figure that this build could not re-check.
FOODS = [
    ["EGG", "EGGS AND DAIRY", "EGG", "egg", 143, 12.6, 9.5, 0.7, 0.0,
     0.89, 0.17, 1.29, 1.75, 30.7, 12, "USDA"],
    ["EGG WHITE", "EGGS AND DAIRY", "EGG", "white", 52, 10.9, 0.2, 0.7, 0.0,
     0.09, 0.01, 0.03, 0.08, 20.0, 11, "REF"],
    ["WHOLE MILK", "EGGS AND DAIRY", "GLASS", "milk", 61, 3.2, 3.3, 4.8, 0.0,
     0.45, 0.04, 0.37, 0.03, 3.7, 11, "REF"],
    ["GREEK YOGURT", "EGGS AND DAIRY", "TUB", "yogurt", 59, 10.2, 0.4, 3.6, 0.0,
     0.75, 0.06, 0.52, 0.07, 9.7, 11, "REF"],
    ["COTTAGE CHEESE", "EGGS AND DAIRY", "TUB", "yogurt", 98, 11.1, 4.3, 3.4, 0.0,
     0.43, 0.05, 0.4, 0.07, 9.7, 8, "REF"],
    ["CHEDDAR", "EGGS AND DAIRY", "CHEESE", "cheese", 403, 22.9, 33.1, 3.1, 0.0,
     1.1, 0.07, 3.1, 0.68, 13.9, 28, "REF"],
    ["MOZZARELLA", "EGGS AND DAIRY", "CHEESE", "white", 300, 22.2, 22.4, 2.2, 0.0,
     2.28, 0.04, 2.9, 0.44, 17.0, 20, "REF"],
    ["PARMESAN", "EGGS AND DAIRY", "CHEESE", "cheese", 392, 35.8, 25.8, 3.2, 0.0,
     1.2, 0.09, 2.75, 0.82, 22.5, 44, "REF"],
    ["BUTTER", "EGGS AND DAIRY", "BUTTER", "butter", 717, 0.9, 81.1, 0.1, 0.0,
     0.17, 0.0, 0.09, 0.02, 1.0, 2, "REF"],
    ["WHEY PROTEIN", "EGGS AND DAIRY", "SCOOP", "whey", 370, 80.0, 3.0, 7.0, 0.0,
     2.0, 0.3, 2.0, 1.0, 20.0, 60, "REF"],
    ["CHICKEN BREAST", "POULTRY", "BREAST", "poultry", 120, 22.5, 2.6, 0.0, 0.0,
     0.21, 0.6, 0.68, 0.37, 17.8, 28, "USDA"],
    ["CHICKEN THIGH", "POULTRY", "THIGH", "poultry", 121, 19.7, 4.1, 0.0, 0.0,
     0.6, 0.35, 1.5, 0.9, 16.0, 22, "REF"],
    ["CHICKEN DRUMSTICK", "POULTRY", "DRUMSTICK", "poultry", 120, 20.1, 3.9, 0.0, 0.0,
     0.5, 0.35, 1.7, 0.8, 15.0, 21, "REF"],
    ["CHICKEN WING", "POULTRY", "WING", "poultry", 222, 18.3, 15.9, 0.0, 0.0,
     0.3, 0.4, 1.3, 0.8, 15.0, 18, "REF"],
    ["TURKEY BREAST", "POULTRY", "BREAST", "poultry", 111, 24.6, 0.7, 0.0, 0.0,
     0.4, 0.6, 1.2, 0.7, 24.0, 28, "REF"],
    ["DUCK BREAST", "POULTRY", "BREAST", "duck", 123, 19.9, 4.2, 0.0, 0.0,
     0.4, 0.4, 1.9, 2.4, 17.0, 21, "REF"],
    ["CHICKEN LIVER", "POULTRY", "LIVER", "liver", 119, 16.9, 4.8, 0.7, 0.0,
     16.6, 0.85, 2.7, 9.0, 54.6, 19, "REF"],
    ["BEEF SIRLOIN", "MEAT", "STEAK", "beef", 130, 21.8, 4.1, 0.0, 0.0,
     1.4, 0.6, 4.3, 1.6, 25.0, 23, "REF"],
    ["BEEF RIBEYE", "MEAT", "STEAK", "beef", 213, 19.5, 14.5, 0.0, 0.0,
     2.1, 0.5, 4.5, 1.8, 21.0, 19, "REF"],
    ["GROUND BEEF", "MEAT", "MINCE", "beef", 215, 18.6, 15.0, 0.0, 0.0,
     2.1, 0.35, 4.5, 2.0, 15.0, 18, "REF"],
    ["BEEF LIVER", "MEAT", "LIVER", "liver", 135, 20.4, 3.6, 3.9, 0.0,
     59.3, 1.08, 4.0, 4.9, 39.7, 18, "REF"],
    ["LAMB CHOP", "MEAT", "CHOP", "lamb", 160, 20.3, 8.3, 0.0, 0.0,
     2.2, 0.13, 3.4, 1.6, 6.0, 23, "REF"],
    ["VENISON", "MEAT", "STEAK", "venison", 120, 22.9, 2.4, 0.0, 0.0,
     2.7, 0.4, 2.1, 3.4, 10.0, 23, "REF"],
    ["PORK LOIN", "MEAT", "CHOP", "pork", 143, 21.4, 5.7, 0.0, 0.0,
     0.6, 0.6, 1.9, 0.8, 32.0, 24, "REF"],
    ["PORK BELLY", "MEAT", "BACON", "pork", 518, 9.3, 53.0, 0.0, 0.0,
     0.5, 0.2, 1.0, 0.6, 12.0, 10, "REF"],
    ["BACON", "MEAT", "BACON", "bacon", 458, 12.6, 45.0, 0.7, 0.0,
     0.6, 0.25, 1.2, 0.6, 20.0, 12, "REF"],
    ["PORK SAUSAGE", "MEAT", "SAUSAGE", "pork", 325, 12.0, 29.0, 2.0, 0.0,
     0.9, 0.2, 1.6, 0.9, 17.0, 12, "REF"],
    ["HAM", "MEAT", "HAM", "ham", 145, 20.9, 5.5, 1.5, 0.0,
     0.7, 0.4, 2.0, 0.9, 20.0, 19, "REF"],
    ["SALMON", "SEAFOOD", "FILLET", "salmon", 208, 20.4, 13.4, 0.0, 0.0,
     3.23, 0.64, 0.36, 0.34, 24.0, 27, "USDA"],
    ["TUNA", "SEAFOOD", "STEAK", "tuna", 109, 24.4, 0.5, 0.0, 0.0,
     2.08, 0.93, 0.37, 0.77, 90.6, 35, "USDA"],
    ["COD", "SEAFOOD", "FILLET", "white", 82, 17.8, 0.7, 0.0, 0.0,
     0.91, 0.24, 0.45, 0.38, 33.1, 32, "USDA"],
    ["HADDOCK", "SEAFOOD", "FILLET", "white", 90, 20.0, 0.6, 0.0, 0.0,
     1.2, 0.3, 0.4, 0.2, 31.0, 29, "REF"],
    ["TILAPIA", "SEAFOOD", "FILLET", "white", 96, 20.1, 1.7, 0.0, 0.0,
     1.6, 0.16, 0.33, 0.56, 41.8, 27, "REF"],
    ["MACKEREL", "SEAFOOD", "WHOLEFISH", "oily", 205, 18.6, 13.9, 0.0, 0.0,
     8.7, 0.4, 0.6, 1.6, 44.0, 76, "REF"],
    ["SARDINES", "SEAFOOD", "SARDINETIN", "oily", 208, 24.6, 11.5, 0.0, 0.0,
     8.9, 0.17, 1.31, 2.9, 52.7, 39, "REF"],
    ["ANCHOVY", "SEAFOOD", "WHOLEFISH", "oily", 131, 20.4, 4.8, 0.0, 0.0,
     0.6, 0.14, 1.7, 3.3, 36.5, 41, "REF"],
    ["TROUT", "SEAFOOD", "WHOLEFISH", "salmon", 141, 19.9, 6.2, 0.0, 0.0,
     4.5, 0.4, 0.4, 0.3, 12.6, 22, "REF"],
    ["SEA BASS", "SEAFOOD", "WHOLEFISH", "white", 97, 18.4, 2.0, 0.0, 0.0,
     0.3, 0.4, 0.4, 0.3, 36.5, 41, "REF"],
    ["SHRIMP", "SEAFOOD", "SHRIMP", "shrimp", 85, 20.1, 0.5, 0.0, 0.0,
     1.1, 0.16, 1.34, 0.52, 29.6, 35, "USDA"],
    ["CRAB", "SEAFOOD", "CRAB", "crab", 87, 18.1, 1.1, 0.0, 0.0,
     9.0, 0.15, 3.5, 0.7, 37.4, 34, "REF"],
    ["LOBSTER", "SEAFOOD", "CRAB", "lobster", 77, 16.5, 0.8, 0.0, 0.0,
     1.4, 0.06, 3.5, 0.3, 41.4, 28, "REF"],
    ["OYSTER", "SEAFOOD", "SHELL", "oyster", 68, 5.2, 1.6, 5.5, 0.0,
     16.2, 0.06, 37.9, 5.78, 63.7, 33, "USDA"],
    ["MUSSEL", "SEAFOOD", "SHELL", "mussel", 86, 11.9, 2.2, 3.7, 0.0,
     12.0, 0.05, 1.6, 3.95, 44.8, 34, "REF"],
    ["SCALLOP", "SEAFOOD", "SHELL", "white", 69, 12.1, 0.5, 3.2, 0.0,
     1.5, 0.06, 0.95, 0.58, 22.2, 22, "REF"],
    ["SQUID", "SEAFOOD", "SQUID", "squid", 92, 15.6, 1.4, 3.1, 0.0,
     1.3, 0.06, 1.53, 0.68, 44.8, 33, "REF"],
    ["ALMONDS", "PLANT", "NUTS", "almond", 579, 21.2, 49.9, 21.6, 12.5,
     0.0, 0.14, 3.1, 3.7, 4.1, 270, "REF"],
    ["WALNUTS", "PLANT", "NUTS", "walnut", 654, 15.2, 65.2, 13.7, 6.7,
     0.0, 0.54, 3.1, 2.9, 4.9, 158, "REF"],
    ["PUMPKIN SEEDS", "PLANT", "NUTS", "seed", 559, 30.2, 49.1, 10.7, 6.0,
     0.0, 0.14, 7.8, 8.8, 9.4, 592, "REF"],
    ["PEANUT BUTTER", "PLANT", "JAR", "peanut", 588, 25.1, 50.4, 20.0, 6.0,
     0.0, 0.44, 2.5, 1.9, 4.1, 154, "REF"],
    ["LENTILS", "PLANT", "LEGUME", "lentil", 353, 25.8, 1.1, 60.1, 10.7,
     0.0, 0.54, 4.8, 7.5, 8.3, 122, "REF"],
    ["CHICKPEAS", "PLANT", "LEGUME", "chickpea", 378, 20.5, 6.0, 63.0, 12.2,
     0.0, 0.54, 3.4, 4.3, 8.2, 79, "REF"],
    ["BLACK BEANS", "PLANT", "LEGUME", "bean", 341, 21.6, 1.4, 62.4, 15.5,
     0.0, 0.29, 3.6, 5.0, 3.2, 171, "REF"],
    ["TOFU", "PLANT", "TOFU", "tofu", 144, 17.3, 8.7, 2.8, 2.3,
     0.0, 0.1, 1.6, 2.7, 17.4, 58, "REF"],
    ["TEMPEH", "PLANT", "TOFU", "tempeh", 192, 20.3, 10.8, 7.6, 0.0,
     0.08, 0.22, 1.1, 2.7, 0.0, 81, "REF"],
    ["EDAMAME", "PLANT", "PODS", "green", 122, 11.9, 5.2, 9.9, 5.2,
     0.0, 0.1, 1.4, 2.3, 0.8, 64, "REF"],
    ["QUINOA", "PLANT", "GRAIN", "grain", 368, 14.1, 6.1, 64.2, 7.0,
     0.0, 0.49, 3.1, 4.6, 8.5, 197, "REF"],
    ["OATS", "PLANT", "GRAIN", "grain", 389, 16.9, 6.9, 66.3, 10.6,
     0.0, 0.12, 4.0, 4.7, 28.9, 177, "REF"],
    ["SPINACH", "PLANT", "LEAF", "green", 23, 2.9, 0.4, 3.6, 2.2,
     0.0, 0.2, 0.53, 2.7, 1.0, 79, "REF"],
    ["KALE", "PLANT", "LEAF", "green", 49, 4.3, 0.9, 8.8, 3.6,
     0.0, 0.27, 0.56, 1.5, 0.9, 47, "REF"],
    ["BROCCOLI", "PLANT", "BROCCOLI", "green", 34, 2.8, 0.4, 6.6, 2.6,
     0.0, 0.18, 0.41, 0.73, 2.5, 21, "REF"],
    ["SWEET POTATO", "PLANT", "TUBER", "sweet", 86, 1.6, 0.1, 20.1, 3.0,
     0.0, 0.21, 0.3, 0.61, 0.6, 25, "REF"],
    ["AVOCADO", "PLANT", "AVOCADO", "avocado", 160, 2.0, 14.7, 8.5, 6.7,
     0.0, 0.26, 0.64, 0.55, 0.4, 29, "REF"],
    ["OLIVE OIL", "PLANT", "BOTTLE", "oil", 884, 0.0, 100.0, 0.0, 0.0,
     0.0, 0.0, 0.0, 0.56, 0.0, 0, "REF"],
    ["TURKEY THIGH", "POULTRY", "THIGH", "poultry", 125, 19.0, 4.9, 0.0, 0.0,
     1.2, 0.35, 2.8, 1.4, 20.0, 22, "REF"],
    ["CHICKEN HEART", "POULTRY", "LIVER", "liver", 153, 15.6, 9.3, 0.7, 0.0,
     7.3, 0.32, 6.6, 9.0, 16.0, 20, "REF"],
    ["PORK TENDERLOIN", "MEAT", "CHOP", "pork", 120, 20.9, 3.4, 0.0, 0.0,
     0.5, 0.8, 1.9, 0.9, 31.0, 25, "REF"],
    ["PROSCIUTTO", "MEAT", "HAM", "ham", 195, 25.0, 10.0, 0.5, 0.0,
     0.8, 0.4, 2.4, 1.0, 25.0, 20, "REF"],
    ["HALIBUT", "SEAFOOD", "FILLET", "white", 111, 22.5, 2.3, 0.0, 0.0,
     1.2, 0.34, 0.43, 0.18, 45.6, 28, "REF"],
    ["CLAM", "SEAFOOD", "SHELL", "oyster", 86, 14.7, 1.0, 3.0, 0.0,
     49.4, 0.09, 1.4, 14.0, 24.3, 9, "REF"],
]

# One serving of each food: grams, and what that looks like. Sizes follow
# US label conventions: 1 oz of cheese or nuts, 1 tbsp of fat, 1 cup of
# milk, and 4 oz raw for meat and fish, which cooks down to about 3 oz.
# A natural unit is used where there is one. Dry goods are weighed dry,
# because that is what the table holds.
MEAT_SERVING = [113, "4 OZ RAW"]
SERVINGS = {
    "EGG": [50, "1 EGG"],
    "EGG WHITE": [33, "1 EGG"],
    "WHOLE MILK": [244, "1 CUP"],
    "GREEK YOGURT": [170, "1 POT"],
    "COTTAGE CHEESE": [113, "1/2 CUP"],
    "CHEDDAR": [28, "1 OZ"],
    "MOZZARELLA": [28, "1 OZ"],
    "PARMESAN": [28, "1 OZ"],
    "BUTTER": [14, "1 TBSP"],
    "WHEY PROTEIN": [30, "1 SCOOP"],
    "BACON": [50, "2 SLICES RAW"],
    "PORK SAUSAGE": [55, "2 LINKS"],
    "HAM": [56, "2 SLICES"],
    "PROSCIUTTO": [28, "1 OZ"],
    "SARDINES": [92, "1 TIN"],
    "ALMONDS": [28, "1 OZ"],
    "WALNUTS": [28, "1 OZ"],
    "PUMPKIN SEEDS": [28, "1 OZ"],
    "PEANUT BUTTER": [32, "2 TBSP"],
    "LENTILS": [48, "1/4 CUP DRY"],
    "CHICKPEAS": [50, "1/4 CUP DRY"],
    "BLACK BEANS": [48, "1/4 CUP DRY"],
    "TOFU": [85, "3 OZ"],
    "TEMPEH": [85, "3 OZ"],
    "EDAMAME": [78, "1/2 CUP"],
    "QUINOA": [43, "1/4 CUP DRY"],
    "OATS": [40, "1/2 CUP DRY"],
    "SPINACH": [30, "1 CUP"],
    "KALE": [67, "1 CUP"],
    "BROCCOLI": [91, "1 CUP"],
    "SWEET POTATO": [130, "1 MEDIUM"],
    "AVOCADO": [50, "1/3 AVOCADO"],
    "OLIVE OIL": [14, "1 TBSP"],
}

def serving(f):
    """Grams and label for one serving. Meat, poultry and seafood not
    listed above share the 4 oz raw portion."""
    if f[0] in SERVINGS:
        return SERVINGS[f[0]]
    if f[1] in ["MEAT", "POULTRY", "SEAFOOD"]:
        return MEAT_SERVING
    return [100, "PER"]

def per(f, i):
    """Column i of a food row, scaled from per 100 g to one serving."""
    return f[i] * serving(f)[0] / 100.0

# One sprite per shape, recoloured per food from the palette.
# 44 columns and 26 rows at most, drawn at x=10, y=3.
SPRITES = {
    "EGG": """
.......HHHHHHH.......
......HMMMMMMDH......
.....HMMMMMMMMDH.....
.....HMMMMMMMMDD.....
....HMMMMMMMMMMDH....
....HMMMGGGGMMMDD....
....HMGGGGGGGDMDD....
....HMGGGGGGGGDMMHHH.
....HGGGGGGGGGGDMMMDH
...HMGGGGGGGGGGDMMMDD
...HMGGGGGGGGGGDMMMDD
..HMMGGGGGGGGGGDMMMDD
..HMMDGGGGGGGGDDMMDD.
..HMMMGGGGGGGDDDMDD..
..HMMMMDGGGGDDDMMDD..
HHMMMMMMDDDDDDMMMDD..
HMMMMMMMMMMMMMMMDD...
HMMMMMMMMMMMMMMMDD...
HDDDDDMMMMMMMMMDD....
.HDDDDDDMMMMMMMDD....
......HDDDDDDDDDD....
........HDDDDDDD.....
""",
    "BREAST": """
.........HHHHHH.....H..................
......HHHMMMMMMHHHHHMHHHHHHHHHHHH......
....HHMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHH.
...HMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMDH
..HMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMDD
.HMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMDD
.HMMMMMMMMMMAAAAAAAAAMMMMMMMMMMMMMMDDD.
HMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMDDD..
HMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMDDD....
HMMMMMMMMMMMMMMMMMMMMMMMMMMMMMDDDD.....
HMMMMMMMMMMMMMMMAAAAAAAAAAMMMDDD.......
HMMMMMMMMMMMMMMMMMMMMMMMMMMDDD.........
HMMMMMMMMMMMMMMMMMMMMMMMMDDDD..........
HMMMMMMMMMMMMMMMMMMMMMMMDDD............
.HMMMMMMMMAAAAAAAAAMMMDDD..............
.HDMMMMMMMMMMMMMMMMMDDDD...............
..HDMMMMMMMMMMMMMMMDDD.................
...HDDMMMMMMMMMMMDDD...................
....HDDDDMMMMMDDDDD....................
......HDDDDDDDDDD......................
.........HDDDD.........................
""",
    "THIGH": """
........HHHHH.........................
.......HMMMMMHH..................H....
.......HMMMMMMMHHHH.H......HHHHHHMHH..
.......HMMDDMMMMMMMHDH....HMMMMMMMMDH.
.......HMDDDDDDDDMMMMMHHHHMMMMMMMMMDD.
......HMMDDDDDDDDDDDDMMMMMMMMMMMMMMMDH
.....HMMMMDDDDDDDDDDDMMMMMMMMMMMMMMMDD
.HHHHMMMMMMMMMMDDDDDDMMMMMMMMMMMMMMDD.
.HMMHHHMMMMMMMMMMMMMMMMAAAAAAAMMMMMDD.
..HMDDDHHHMMMMMMMMMMMMMMMMMMMMMMMDDD..
.HMMMMDDDDHHHHMMMMMMMMMMMMMMMMMMDDD...
HMMMMMMMMMDDDDHHHHHHHHMMMMMMMMMDD.....
HMMMMMMMMMMMMDDDDDDDDDHHHHHHMMDD......
HMMMMMMMMMMMDDDDMMMMMDDDDDDDMDD.......
HDMMMMMMMMMDDDDDDDDMMMMMMMMMDD........
.HDDMMMMMDDD....HDDDDMMMMMMMDD........
..HDDDDDDDD........HDDMMMMMDDD........
....HDDDD............HDDDDDDDD........
......................HDDDD...........
""",
    "DRUMSTICK": """
.............................G......
...........................GGGGG....
...........................GGGGGG...
..........................GGGGGGGG..
...........................GGGGGGD..
..........................GGGGGGGGGG
................HHHHHHHHGGGGGGGGGGGD
............HHHHMMMMMMMMMGGGGGGGGGGD
.......HHHHHMMMMMMMMMMMMMMGGGGDGGGGD
.....HHMMMMMMDDMMMMMMMMMMMGGGD.GDDD.
...HHMMMMMMMMMMDDMMMMMMMMMGGD.......
..HMMMDDDMMMMMMMMDDMMMMMMDGD........
.HMMMMMMDDDMMMMMMMMMMMMMMDD.........
.HMMMMMMMMDMMMMMMMMMMMMDD...........
HMMMMMMMMMMMMMMMMMMMMMMDD...........
HMMMMMMMMMMMMMMMMMMMMDD.............
HMMMMMMMMMMMMMMMMMMMMDD.............
.HMMMMMMMMMMMMMMMMMMDD..............
.HMMMMMMMMMMMMMMMMMMDD..............
.HDDMMMMMMMMMMMMMMMDDD..............
..HDDMMMMMMMMMMMMMDDD...............
....HDDDMMMMMMMDDDD.................
.....HDDDDDDDDDDDD..................
........HDDDDDD.....................
""",
    "WING": """
.................HHH...................
...............HHMMMHH.................
...............HMMMMMMHH...............
..............HMMMMMMMMMHHH............
..............HMMMMMMMMMMMMHH..........
..............HMMMMMDDMMMMMMMHH........
.............HMMDMMMMDDDMMMMMMDH.......
..........HHHMMDMDDMMMMDDDDMMMMDH......
........HHMMMMDMMDDDDDMMMMDDDMMMDH.....
.....HHHMMMMMDMDD..HDDDDDMMMDDMMDD.....
...HHMMMMMMMMMMDD.....HDDDDMMMMMMDH....
..HMMMMMMMMMMMDD........HDDDDMMMMMDH...
.HMMMMMMMMMMMMDD...........HDDDMMMDD...
.HMMMMMMMMMMMMDD.............HDDMMMGG..
HMMMMMMMMMMMMDD................HDMGGGG.
HMMMMMMMMMMMMDD.................HGGGGGG
HMMMMMMMMMMMMDD..................GGGGGD
HMMMMMMMMMMMMDD...................GDDD.
.HMMMMMMMMMMDD.........................
.HDMMMMMMMMMDD.........................
..HDDMMMMMDDD..........................
...HDDDDDDDD...........................
.....HDDDD.............................
""",
    "LIVER": """
....HHHHHHHHHHHHH.....................
..HHMMMMMMMMMMMMDH....................
..HMMMMMMMMMMMMMDD....................
.HMMMMMMHMMMMMMMMDH...................
.HMMMHHHHHHHMMMMMMDH..................
.HMMHHHHHHHHHMMMMMMMHH................
.HMMHHHHHHHHHMMMMMMMMMHHHHH...........
HMMMMHHHHHHHMMMMMMMMMMMMMMMHHH........
HMMMMMMMHMMMMMHMMMMMMMMMMMMMMMHH......
HMMMMMMMMMMMHHHHHMMMMMMMMMMMMMMDH.....
HMMMMMMMMMMMHHHHHMMMMMMMMMMMMMMDD.....
HMMMMMMMMMMMMMHMMMMMMMMMMMMMMMMMMHHH..
.HMMMMMMMMMMMMMMMMMMMHHHMMMMMMMMMMMDH.
.HDMMMMMMMMMMMMMMMMMHHHHHMMMMMMMMMMMDH
..HDMMMMMMMMMMMMMMMMMHHHMMMMMMMMMMMMDD
...HDMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMDD
....HDDDMMMMMMMMMDDMMMMMMMMMMMMMMMMDDD
.....HDDDDDDDDDDDDDDDDMMMMMDDDDDDDDDD.
........HDDDDDDDD..HDDDDDDDDDDDDDDD...
......................HDDDD...........
""",
    "STEAK": """
..........HHHHHHHHHHHHHHHAA.........
.........HMMMMMMMMMMMMMMMAAA........
........HMMMMMMMMMMMMMMMMMAAA.......
......HHMMMMMMMMMMMMMMMMMMMAAA......
.....HMMMMMMMMMMHHHHMMMMMMMMAAA.....
....HMMMMMMMMMMMMMMMHHHHMMMMMAAAA...
...HMMMMMMMMMMMMMMMMMMMMMMMMMMAAAA..
.HHMMMMMHHHHMMMMMMMMMMMMMMMMMMMAAAA.
HDMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMAAAA
.HDMMMMMMMMMMMMMMMMMMMMMMMMMMMMAAAD.
..HDMMMMMMMMMMMMMMMMMMMMMMMMMMAAAD..
...HDMMMMMMMHHHHHMMMMMMMMMMMMAAAD...
....HMMMMMMMMMMMHHHHHMMMMMMMAAAD....
.....HMHHHMMMMMMMMMMMMMMMMMAAAD.....
.....HDMMMHHHMMMMMMMMMMMMMAAAAD.....
......HDMMMMMMMMMMMMMMMMMAAAAD......
.......HDMMMMMMMMAAAAAAAAAAAD.......
........HDDDDDDDDAAAAAAAAAAD........
.........HDDDDDDDDDDDDDDDDD.........
""",
    "MINCE": """
..............HHHHHH..............
..............HMMDMDH.............
..........HHHHMMMDMMMHHHHH........
..........HMMDMDD.HMDMMMMDH.......
......HHHHMMMDMMMHMMDMMMDD........
.....HMMMDMDD.HMMDDD.HMMDD........
....HMMMADAAMHMMMDMMHMMMDD.HHH....
....HMMDD.HADMMDD.HMMMMMDD.HDDH...
....HMMMMHMMDMMMMHDMMMMMMMHMDMDH..
...HMMMDMMDD.HMMDD.HAMMMDMDD.HDD..
..HMMMMDDMMMHMMMDMHMMMMMDMMMHMDD..
.HMMMDD.HMMMMMDD.HMMMDDD.HMMMDD...
..HMMDD..HMMMMDMHMAAADAMHMMMMDD...
..HMMMDH.HDMDD.HMDADD.HMDMMMMDD...
..HMMMMMHMDMMMHMMDMMAHAMDAAMDD..HH
..HMMMDMDD.HMDMDD.HMDMDD.HMMDD.HDD
.HMMMDDDMMHMDDDMMHMDDDAAHMMDDDHMDD
HDDDDD.HDDDDD.HDDDDD.HDDDDDD.HDDDD
.HDDD...HDDD...HDDD...HDDDD...HDD.
""",
    "CHOP": """
.........AAAAAAAAAAA.....................
......AAAAAAAAAAAAAAAAH..................
.....AAAAAMMMMMMMMMMMMMHH................
...AAAAAMMMMMMMMMMMMMMMMMHH..............
..AAAAMMMMMMMMMMMMMMMMMMMMDH.............
.AAAAMMMMMMMMMMMMMMMMMMMMMMDH............
.AAAMMMMMMMMMMMMMMMMMMMMMMMDD........GGG.
AAAMMMMMMMMMMMMMMMMMMMMMMMMMMGGGGGGGGGGGG
AAAMMMMMMMHHHHHMMMMMMMMMMMMMMMGGGGGGGGGGD
AAMMMMMMMMMMMMHHHHHMMMMMMMMMMGGGGGGGGGGGD
AAMMMMMMMMMMMMMMMMMMMMMMMMMMMGGGGGGGGGGGD
AAMMMMMMMMMMMMMMMMMMMMMMMMMMMGGGGGGGGGGGD
AAMMMMMMMMMMMMHHHHHMMMMMMMMMDGGGGGGGGGGGD
AAAMMMMMMMMMMMMMMMMHHHHHMMMMDDDDDDDDDGGGD
.AAMMMMMMMMMMMMMMMMMMMMMMMDD.........GDD.
.AAAMMMMMMMMMMMMMMMMMMMMMMDD.............
..ADDMMMMMMMMMMMMMHHHHHHDDD..............
...HDDMMMMMMMMMMMMMMMMMDDD...............
.....HDDDMMMMMMMMMMMDDDD.................
......HDDDDDDDDDDDDDDDD..................
.........HDDDDDDDDDD.....................
""",
    "BACON": """
..........HH..............HH..............
........HHMMHH..........HHMMHH..........HH
.......HMMAAMMHH.......HMMAAMDH.......HHDD
H....HHMAAMMAAMDH....HHMAAMMAAMHH....HMMDD
HHHHHMMAMMAAMMAAMHHHHMMAMMAAMMAMMHHHHMAADD
HMMMMAAMAADDAAMMAMMMMAAMAADDAAMAAMMMMAMMDD
HAAAAMMADDDDDDAAMAAAAMMADDDDDDAMMAAAAMAADD
HMMMMAADDD..HDDDAMMMMAADDD..HDDAAMMMMADDDD
HAAAADDD......HDDAAAADDD......HDDAAAADDD..
HDDDDDD.........HDDDDDD........HDDDDDD....
.HDDD............HDDD............HDDD.....
..........................................
...HHHH...........HHHHH...........HHHH....
.HHMMMDH.........HMMMMDH.........HMMMMHH..
HMMAAAAMHH......HMAAAAADH......HHMAAAAMDH.
HAAMMMMAMDH...HHMAMMMMMAMHH...HMMAMMMMAADH
HMMAAAAMAAMHHHMMAMAAAAAMAMMHHHMAAMAAAAMMDD
HAADDDDAMMAMMMAAMADDDDDAMAAMMMAMMADDDDAADD
HDDDDDDDAAMAAAMMADDDDDDDAMMAAAMAADDDDDDDDD
HDD....HDDAMMMAADD.....HDAAMMMADDD....HDDD
H.......HDDAAADDD.......HDDAAADDD.......HD
..........HDDDDD.........HDDDDD..........H
...........HDD.............HDD............
""",
    "SAUSAGE": """
............HHHHHHHHHHHH.................
.........HHHMMMMMMMMMMMMHHH..............
.......HHMMMMMMMMMMMMMMMMMMHHH...........
.....HHMMMMMMMMMMMMMMMMMMMMMMMHH.........
....HMMMMMMMMMMMMMMMMMMMMMMMDMMMHH.......
..HHMMMDMMMMMMMMMMMMMMMMMMMMDMMMMDH......
.HMMMMMDMMMMMDDDDDDDDDDDMMMMDMMMMMDH.....
HMMMMMMDMDDDDDDDDDDDDDDDDDDDDDMMMMDD.....
HMMMMMMDDDDDD...........HDDDDDDMMMDD.....
HDMMMDDDD....................DDDDDD......
.HDDDDD..............H.........HDD.......
..HDD..........HHHHHHMHHHHHH.............
............HHHMMMMMMMMMMMMMHHHH.........
..........HHMMMMMMMMMMMMMMMMMMMMHH.......
........HHMMMMMMMMMMMMMMMMMMMMMMMMHHH....
......HHMMMMMMMMMMMMMMMMMMMMMMMMMDMMMHH..
....HHMMMDMMMMMMMMMMMMMMMMMMMMMMMDMMMMDH.
...HMMMMMDMMMMMMDDDDDDDDDDDDDMMMMDMMMMMDH
..HMMMMMMDMMDDDDDDDDDDDDDDDDDDDDDDDMMMMDD
..HMMMMMMDDDDDDD.............HDDDDDDMMMDD
..HDMMMDDDDD.....................HDDDDDD.
...HDDDDD...........................HDD..
....HDD..................................
""",
    "HAM": """
.....................GGGGGGGG..........
.......GGGGGGGGGGGGGGGGGMGGGGGG........
.....GGGGMMMMGGGGGGMMMMMMMMMGGGG.......
....GGMMMMMMMMMMMMMMMMMMMMMMMGGD.......
...GGGMMMMMMMMMMMMMMMMMMMMMMMMGD.......
...GGMMMMMMMMMMMMMMMMMMMMMMMMMGD.......
....GMMMMMMMMMMMMMMMMMMMMMMMMMGGG......
....GMMMMMMMMMMMMMMMMMMMMMMMMMMGGG.....
....GGMMMMMHHHHHHMMMMMAAMMMMMMMMGGG....
....GMMMMMMMMMMMHHHHHHMMMMMMMMMMMGGG...
...GGMMMMMMMMMMAAMMMMMMMMMMMMMMMMMMGG..
..GGMMMMMMMMMMMMMMMMMMMMMAAMMMMMMMMGGG.
.GGMMMMMMMMMMMHHHHHHMMMMMMMMMMMMMMMGGGG
GGGMMMMMMMMMAAMMMMMMHHHHHHMMMMMMMMMGGGD
GGGMMMMMMMMMMMMMMMMAAMMMMMMMMMMMMMGGGD.
.GGGMMMMMMHHHHHHMMMMMMMAAMMMMMMGGGDDD..
.GDGGGMMMMMMMMMHHHHHHMMMMMMGGGGDDD.....
...GDGGGGGGGMMMMMMMMMMMMMMGGGDD........
.....GDDDDDDGGMMMMMMMMMMMGGGD..........
............GGGGMMMMMMMMGGGD...........
.............GDGGGGMMGGGGGD............
...............GDGGGGGGGDD.............
.................GDDDDDD...............
""",
    "FILLET": """
.........H................................
........HMHHHHHHHHH.......................
.......HMMMDMMMMMMMHH.....................
......HMMMMDMMMMMMMMDHH...................
.....HMMMMMDMMMMMMMMDMDH..................
....HMMMMMMMDMMMMMMMDMMMHH................
...HMMMMMMMMDMMMMMMMDMMMMMHH..............
...HMMMMMMMMDMMMMMMMDDMMMMMDH.............
..HMMMMMMMMMDMMMMMMMMDMMMMMMMHH...........
..HMMMMMMMMMDMMMMMMMMDMMMMMMMDDH..........
.HMMMMMMMMMMMDMMMMMMMDMMMMMMMDMMHH........
.HMMMMMMMMMMMDMMMMMMMDMMMMMMMDMMMDH.......
HMMMMMMMMMMMMDMMMMMMMDMMMMMMMDMMMMMHH.....
HMMMMMMMMMMMMDMMMMMMMDMMMMMMMMDMMMMMDH....
HMMMMMMMMMMMMDMMMMMMMDDMMMMMMMDMMMMMMDH...
HMMMMMMMMMMMMMDMMMMMMMDMMMMMMMDMMMMMMMMHH.
HMMMMMMMMMMMMMDMMMMMMMDMMMMMMMDMMMMAAAAAAA
HMMMMMMMMMMMMMDMMMMMMMDMMMMMMAAAAAAAAAAAAD
HMMMMMMMMMMMMMAAAAAAAAAAAAAAAAAAAAADDDDDDD
AAAAAAAAAAAAAAAAAAAAAAAAAAAAADDDDDD.......
AAAAAAAAAAAAAADDDDDDDDDDDDDDD.............
AAAAAAAAAAAADD............................
""",
    "WHOLEFISH": """
...................H.....................
..................HDH...................H
................HHMMDH...............HHHD
...............HMMMMMDH............HHMMDD
..............HMMMMMMMMHH.......HHHMMMMDD
..........HHHHMMMMMMMMMMDH....HHMMMMMMMDD
.......HHHMDMMMMMMMMMMMMMMHHHHMMMMMMMMMDD
......HDMMMDMMMMMMMMMMMMMMMMMMMMMMMMMMMDD
....HGGGDMMDMMMMMMMMMMMMMMMMMMMMMMMMMDDD.
.HHHDGDGDDMDMMMMMMMMMMMMMMMMMMMMMMMMDDD..
HDDMDGGGDDMDMMMMMMMMMMMMMMMMMMMMMMMDD....
.HDDMDDDDMDMMMAAAAAAAMMMMMMMMMMMMMDD.....
...HMMDDMMDMMMMMMMMMAAAAAAAMMMMMMMMDH....
....HDMMMMDMMMMAAAAAAMMMMMMMMMMMMMMMMHH..
....HDDMMMDMMMMMMMMMAAAAAAMMMMMMMMMMMMDH.
......HDDDDMMMMMMMMMMMMMMDDDDDMMMMMMMMMDH
.......HDDDDDDDDMMMMMDDDDDDDDDDDMMMMMMMDD
..........HDDDDDMMMMMDDDD.....HDDDDMMMMDD
................HMMDD...........HDDDDMMDD
................HDMDD..............HDDDDD
.................HDD.................HDDD
..................H.....................H
""",
    "SARDINETIN": """
...............................HHHHH..
..............................HMDDDDH.
............................HHMDD.HDDH
........................HHHHMMDD...HDD
...................HHHHHMMMDDDD.....HD
...............HHHHMMMMDDDDDDDDH...HDD
..........HHHHHMMMMMMMMDDDD..HDDH.HMDD
......HHHHMMMMMMMMMMMDD.......HMMHDDD.
.......HMMMMMMMMMMMMMMMHHHHHH..HMDDD..
....HHHMMMMMMMMMMMMMMMMMMMMMMHHAD.....
..HHMMMMMMMMMMMMMMDMMMMMMMMMMMMMMHH...
.HMMMMDAAAAAAAAAAAAAAAAADDAAAAAMMMDH..
.HMMDAAAAAAAAAAAAAAAAAAAAADDDDDDDMDD..
.HMDDADDAAAAAAAAAAAAAAAAAAAAADDDDDDD..
.HMDDDADDDDDDDDDDDDDDDAAADDDAAADDDDD..
HMMDDDDDDDDDAAAAAAADDDDDDDDDDDDADDDDH.
.HMDDDDDDDAAAAAAAAAAADDDDDDAAAADDDDD..
.HMDDDAAAAAAAAAAAAAAAAAAAAAAADDDDDDD..
.HMMDADDAAAAAAAAAAAAAAAAAADDDDDDDDDD..
.HDDMAADDDDDDDDDDDDDDDAAAADAAAADDDDD..
..HDDDDDAAAAAAAAAAAAAAADDDDDDAAADDD...
....HDDDDDDDDDDDDDDDDDDDDDDDDDDAD.....
........HDDDDDDDDDDDDDDDDDDDD.........
""",
    "SHRIMP": """
...............HHHHH...............
..........HHHHHMMMMMHHHHH..........
.......HHHMMMDMMMMMMMMMMDH.........
......HMMMMMMDDMMMMMMMMMMDH........
....HHMMMMMMMMDMMMMMMMMMMDD........
...HDMMMMMMMMMDMMMMMMMMMMDD........
..HMMDMMMMMMMMDMMMMMMMMMMDD........
.HMMMMDDMMMMMMDMMMMMMMMMMDD........
.HMMMMMDDMDDDDDDDDDDMMMMDDD........
.HMMMMMMDDDDDDDDDDDDDDDDDD.........
HMMMMMMMDD..........HDDD...........
HDDDDDDD...........................
HMMMMMDD...........................
.HMMMMDD....................HHHH...
.HMMMMMMHD...............HHHMMDD...
.HDMMMMDDMHH..........HHHMMMMMDD...
..HDMMDDMMMMHHHHHHHHHHMMMMMMMDD....
...HDDMMMMMMMMDMMMMMMMMMMMMMMMMHHHH
....DDDDDMMMMMDMMMMMMMMMMMMMMMMMMDD
......HDDDDDDDDDDDDDDDDDMMMMMDDDDDD
.........HDDDDDDDDDDDDDDDDMMMDDDDDD
........................HDDDD......
..........................HDD......
""",
    "CRAB": """
..HH.................................HH..
.HMMHH.............................HHMDH.
.HDMMMHH.........................HHMMMDD.
..HMMMMDH.......................HMMMMDD..
...HMMMMDH.....................HMMMMDD...
.HHMMMMMMMHH...HHHHHHHHHHH...HHMMMMMMMHH.
HMMDDDDMMMMMHHHMMMMMMMMMMMHHHMMMMMDDDDMDH
HDDDDDDDDMMMMMMMMMMMMMMMMMMMMMMMDDDDDDDDD
.HD....HDMMMMMMDDMMMMMMMDDMMMMMMDD....HD.
.........HMMMMMDDMMMMMMMDDMMMMDD.........
........HMMMMMMMMMMMMMMMMMMMMMMDH........
........HMMMMMMMMMMMMMMMMMMMMMMDD........
........HMMMMMMMMMMMMMMMMMMMMMMDD........
........HMMMMMMMMMMMMMMMMMMMMMMDD........
......HHMMMMMMMMMMMMMMMMMMMMMMMMMHH......
...HHHMDDDMMMMMMMMMMMMMMMMMMMMMDDDMHHH...
..HMDDDDDDMMMMMMMMMMMMMMMMMMMMMDDDDDDDH..
..HDDDD...HMMMMMMMDDMDDMMMMMMDD...HDDDD..
...H....HHMDMMMMMDDDDDDDMMMMMDMHH....H...
......HHMDDDMMMDDD..H..HDDMMMDDDMHH......
.....HDDDDD.HMDDD.......HDDDD.HDDDDH.....
.....HDDD..HDDD...........HDDH..HDDD.....
...........HDD.............HDD...........
""",
    "SHELL": """
...............H...................
..............HDH....H.............
.........HHHHHMMMHHHHDH............
........HMMMMMMMMMMMMMMHHHHH.......
........HMMMMMMMMMMMMMMMMMDD.......
.......HMMMMMMMMMMMDMMMMMMMDH......
....HHHMMMMMMMDMMMMDMMMMMMMDD......
....HMMMMMMMMMDDMMMDMMMDMMMMMHHH...
...HMMMMMDDMMMMDMMMDMMMDMMMMMMDD...
...HMMMMMMDDMMMDMMMDMMDDMMMDMMMDH..
..HMMMMMMMMDDMMDDMMDMMDMMMDMMMMDD..
.HDMMMMMMMMMDMMMDMMDMMDMMDDMMMMMDH.
HDDDDMDDDMMMMDMMDGMGMDMMDDMMMMMDDDH
...HDDDDDDMMMMGGGGGGGGDDDMMMDDDDD..
.....HDDDDDDMGGGGGGGGGGDMMDDDDD....
........HDDDDGGGGGGGGGGDDDDDD......
...........HDDGGGGGGGGGDDD.........
.............HDDGGGGGDDDDD.........
.............HDDDDDDDDMMDD.........
.............HDDDDDDDDDDDD.........
...............HDDDDDDDD...........
""",
    "SQUID": """
.................................H........
..............................HHHDH.......
.............................HMDDD........
.......H...................HHMDD..........
......HMHH................HMMDD....HHH....
.....HMMMMHHHHHHH.........HMMMMHHHHDDDH...
....HMMMMMMMDDMMMHHH..HHHHMMMMMMMMDDDD....
...HMMMMMDDDMMMMMMMMHHDMMMMMMMMMDD....HHH.
..HMMMDDDMMMMMMMMMMMMDDMMMMMMMMMMMHHHHDDDH
HHMMDDMMMMMMMMMMMMMMMMMMMMMMMMMMMMMDDDDDD.
HDMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMDD.......
HDDMDDMMMMMMMMMMMMMMMMMMMMMMMMMMMMMHH.....
..HDMMDDDMMMMMMMMMMMDDDMMMMMMMMMMMDDDHHHH.
...HDMMMMDDDMMMMMDDDDDDDDDMMMMMMMMDDDDDDDH
....HDMMMMDDDDDDDDDD..HDDDMMMMMMDD.....HD.
.....HDMDDDDDDDDD.........HMMMMMDDHH......
......HDDD................HDMMMMDDDDHH....
.......H...................HDDDD..HDDDH...
............................HDDDH....H....
..............................HDDH........
...............................HDDH.......
.................................H........
""",
    "GLASS": """
HHHHHHHHHHHHHHHHHHHH
HMDDDDDDDDDDDDDDDDMD
HMDDDDDDDDDDDDDDDDMD
HMDDDDDDDDDDDDDDDDMD
HMDDDDDDDDDDDDDDDDMD
HMDDDDDDDDDDDDDDDDMD
HMDDDDDDDDDDDDDDDDMD
HMHHHHHHHHHHHHHHHHMD
HMGGGGGGGGGGGGGGDDMD
HMGGGGGGGGGGGGGGDDMD
HMGGGGGGGGGGGGGGDDMD
HMGGGGGGGGGGGGGGDDMD
HMGGGGGGGGGGGGGGDDMD
HMGGGGGGGGGGGGGGDDMD
HMGGGGGGGGGGGGGGDDMD
HMGGGGGGGGGGGGGGDDMD
HMGGGGGGGGGGGGGGDDMD
HMGGGGGGGGGGGGGGDDMD
HMGGGGGGGGGGGGGGDDMD
HMGGGGGGGGGGGGGGDDMD
HMGGGGGGGGGGGGGGDDMD
HMGGGGGGGGGGGGGGDDMD
HMDDDDDDDDDDDDDDDDMD
HMDDDDDDDDDDDDDDDDMD
HMDDDDDDDDDDDDDDDDDD
""",
    "TUB": """
HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH....
GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG.
GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG.
GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGDD..
GDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD....
..HHMMMMMMMMMMMMMMMMMMMMMMMMMMDD......
..HHDDDDDDDDDDDDDDDDDDDDDDDDDDDD......
...HHMMMMMMMMMMMMMMMMMMMMMMMMDD.......
...HHMMMMMMMMMMMMMMMMMMMMMMMMDD.......
....HHMMMMMMMMMMMMMMMMMMMMMMDD........
....HHMMMMMMMMMMMMMMMMMMMMMMDD........
.....HHMMMMMMMMMMMMMMMMMMMMDD.........
.....HHMMMMMMMMMMMMMMMMMMMMDD.........
......HHMMMMMMMMMMMMMMMMMMDD..........
......HHMMMMMMMMMMMMMMMMMMDD..........
.......HHMMMMMMMMMMMMMMMMDD...........
.......HDDDDDDDDDDDDDDDDDDD...........
......................................
......................................
""",
    "CHEESE": """
............................GG....
..........................HHGG....
........................HHHHGG....
......................HHHHHHGG....
....................HHHHHHMDGG....
..................HHHHHHMMMDGG....
................HHHHHHDDDMMDGG....
..............HHHHHHMMDDMMMDGG....
............HHHHHHMMMMMMMMMDGG....
..........HHHHHHDDMMMMMMMMMDGG....
........HHHHHHMDDDDMMMMMMMMDGG....
......HHHHHHMMMMDDMMMMMMMMMDGG....
....HHHHHHMMMMMMMMMMMMMMMMMDGG....
....HHHHMMMMMMMMMMMMMMMMMMMDGG....
....HHMMMMMMMMMMMMMMMMMMMMMDGG....
..MMDDDDDDDDDDDDDDDDDDDDDDDDDD....
..................................
..................................
""",
    "BUTTER": """
........................................
........................................
........................................
...............HHHHHHHHGGGGGGGHHHHHHH...
..............HHHHHHHHDGGGGGGDHHHHHDD...
.............HHHHHHHHDGGGGGGDHHHHHDDD...
............HHHHHHHHDGGGGGGDHHHHDDDDD...
............MMMMMMMMDGGGGGGDMMMMDDDDD...
............MMMMMMMMDGGGGGGDMDMMDDDDD...
............MMMMMMMMDGGGGGGDMDMMDDDDD...
..HHHHHHHHH.MMMMMMMMDGGGGGGDMDMMDDDDD...
.HHHHHHHHDD.MMMMMMMMDGGGGGGDMDMMDDDDD...
HHHHHHHDDDD.MMMMMMMMDGGGGGGDMDMMDDDDD...
MMMMMMMDDDD.MMMMMMMMDGGGGGGDMDMMDDDDD...
MMMMMMMDDDD.MMMMMMMMDGGGGGGDMDMMDDDD....
MMMMMMMDDDD.MDDDDDDDDGGGGGGDDDDDDDD.....
MDDDDDDDDD..MDDDDDDDDGGGGGGDDDDDDD......
MDDDDDDDD...............................
........................................
""",
    "SCOOP": """
........HHHH..HHH...................
......HHAAAAAAAADM..................
.....HHAAAAAAAAAADM.................
....HHAAAAAAAAAAAADM................
...HHAAAAAAAAAAAAAADHHHHHHHHHHHHH...
HHAAAAAAAAAAAAAAAAADDMMMMMMMDDDMMM..
HAHHHHHHHHHHHHHHHHHDDMMMMMMMDDDMMD..
AAHMMMMMMMMMMMMMMMMDDDDDDDDDDDDDD...
ADHMMMMMMMMMMMMMMMMDD...............
...HMMMMMMMMMMMMMMDD................
...HMMMMMMMMMMMMMMDD................
....HMMMMMMMMMMMMDD.................
....HMMMMMMMMMMMMDD.................
.....HMMMMMMMMMMDD..................
.....HMMMMMMMMMMDD..................
......HMMMMMMMMDD...................
......HMMMMMMMMDD...................
.......MDDDDDDDD....................
....................................
....................................
""",
    "NUTS": """
..........HHHH................
........HHMMMMM...............
......HHMMMMMMDM.....HHHH.....
.....HHMMMMMMMDD...HHMMMMM....
......HMMMMMMMDD.HHMMMMMMDM...
.......MMMMMMMD.HHMMMMMMMDD...
.........HDDD....HMMMMMMMDD...
.......HHHH.......MMMMMMMD....
.....HHMMMMM........HDDD......
...HHMMMMMMDM.....HHHH........
..HHMMMMMMMDD...HHMMMMM.......
...HMMMMMMMDD.HHMMMMMMDM......
....MMMMMMMD.HHMMMMMMMDD......
......MDDD....HMMMMMMMDD......
...............MMMMMMMD.......
.................MDDD.........
..............................
""",
    "JAR": """
HHHHHHHHHHHHHHHHHHHHHH..
HDMMMMDDMMMMDDMMMMDDMM..
HDMMMMDDMMMMDDMMMMDDMM..
HDDDDDDDDDDDDDDDDDDDDD..
......HAAAAAAAAD........
....HAAAAAAAAAAAAA......
...HAAAAAAAAAAAAAAA.....
...HAAAAAAAAAAAAAAD.....
...HAAAAAAAAAAAAAAD.....
...HAAAAAAAAAAAAAAD.....
...HAAAAAAAAAAAAAAD.....
...HDDDDDDDDDDDDDDD.....
...HGGGGGGGGGGGGGGD.....
...HGGGGGGGGGGGGGGD.....
...HGGDDDDDDDDDDGGD.....
...HGGGGGGGGGGGGGGD.....
...HGGDDDDDDDDDDGGD.....
...HGGGGGGGGGGGGGGD.....
...HDDDDDDDDDDDDDDD.....
...HAAAAAAAAAAAAAAD.....
...HAAAAAAAAAAAAAAD.....
...HDDDDDDDDDDDDDDD.....
........................
""",
    "LEGUME": """
..........HHH.................
.........HAAAA.HHH............
.........HAAADHAAAA...........
........HHDDD.HAAADHH.........
.......HAAAD.HHDDDAAAA........
.......HAAADHAAADHAAAD........
.....HHHDDD.HAAADHDDD.........
....HAAAD.HHHDDDAAD.HHH.......
....HAAADHAAADHAAADHAAAA......
...HHDDD.HAAADHDDD.HAAADHH....
..HAAAD.HHDDDAAAD.HHDDDAAAA...
..HAAADHAAADHAAADHAAADHAAAD...
.HHDDD.HAAADHDDD.HAAADHDDD....
HAAAD.HHDDDAAAD.HHDDDAAADHHH..
HAAADHAAADHAAADHAAADHAAAHAAAA.
.ADD.HAAAD.ADD.HAAAD.ADDHAAAD.
......ADD.......ADD......ADD..
..............................
""",
    "TOFU": """
..........................
..........................
......HHHHHHHHHHHHHHHHHM..
.....HHHHHHHHHHHHHHHHHMD..
....HHHHHHHHHHHHHHHHHMDD..
...HHHHHHHHHHHHHHHHHMDDD..
..HHHHHHHHHHHHHHHHDDDDDD..
..HHHMMMMMMMMMMMMMDDDDDD..
..HHMMMMMMMMMMMMMMDDDDDD..
..HMMMMMMMMMMMMMMMDDDDDD..
..HMMMMMMMMMMMMMMMDDDDDD..
..HMMMMMMMMMMMMMMMDDDDDD..
..HMMMMMMMMMMMMMMMDDDDDD..
..HMMMMMMMMMMMMMMMDDDDDD..
..HMMMMMMMMMMMMMMMDDDDDD..
..HMMMMMMMMMMMMMMMDDDDD...
..HMMMMMMMMMMMMMMMDDDD....
..HDDDDDDDDDDDDDDDDDD.....
..HDDDDDDDDDDDDDDDDD......
..........................
..........................
""",
    "PODS": """
.....HHH...HHH...HHH............
...HHHHHHHHHHHHHHHHHHH..........
.HHHHHHHHDHHHHHDHHHHHHHH........
HHHAAAAAADAAAAADAAAAAAHHHH......
HDDAAAAAADAAAAADAAAAAADDHH......
.HDDDAAADDDAAADDDAAADDDD........
...HDDDDDDDDDDDDDDDDDD..........
.....HDD...HDD...HDD............
................................
................................
...........HHH...HHH...HHH......
.........HHHHHHHHHHHHHHHHHHH....
.......HHHHHHHHDHHHHHDHHHHHHHH..
......HHHAAAAAADAAAAADAAAAAAHHHH
......HDDAAAAAADAAAAADAAAAAADDHH
.......HDDDAAADDDAAADDDAAADDDD..
.........HDDDDDDDDDDDDDDDDDD....
...........HDD...HDD...HDD......
................................
................................
""",
    "GRAIN": """
............HHHH................
...........HAAAAHHHHH...........
............HDDDHAAAAH..........
.........HHHH....HDDDHH.........
........HAAAAA.HHHHAAAAA........
.........HDDD.HAAAADDDD.........
.......HHHH....HDDDHHHH.........
......HAAAAA.HHHH.HAAAAA........
.......HDDD.HAAAAH.HDDD.........
.....HHHH....HDDDHHHH...........
....HAAAAA.HHHH.HAAAAHHHHH......
.....HDDD.HAAAAH.HDDDHAAAAH.....
...HHHH....HDDDHHHH...HDDDHHH...
..HAAAAA.HHHH.HAAAAA.HHHHAAAAA..
...HDDD.HAAAAH.HDDD.HAAAADDDD...
.HHHH....HDDDHHHH....HDDDHHHH...
HAAAAA.HHHH.HAAAAA.HHHH.HAAAAA..
.ADDD.HAAAAA.ADDD.HAAAAA.ADDD...
.......ADDD........ADDD.........
................................
................................
""",
    "LEAF": """
...............HHH..............
.............HHAAAAA............
...........HHAAHDAAAAA..........
............HHAHDAAAADA.........
........HHAAAAAHDAAADD..........
.......HHAAAAADHDDAAAAAAA.......
........HHAAADAHDADAAAAADA......
.....HHAAAAADAAHDAADAAADD.......
....HHAAAAAAAAAHDAAAAAAAAAAA....
.....HHAAAAAAADHDDAAAAAAAAADA...
...HHAAAAAAAADAHDADAAAAAADD.....
..HHAAAAAAAADAAHDAADAAAAAAAAAA..
....HHAAAAAAAAAHDAAAAAAAAAAADD..
...HHAAAAAAAAADHDDAAAAAAADD.....
....HHAAAAAAADAHDADAAAAAAADA....
.......HHAAADAAHDAADAAAAADD.....
......HHAAAAAAAHDAAAAADD........
........HHAAAAAHDAAAAADD........
..........HHAAAHDAAADD..........
............ADDMDDDD............
...............MD...............
...............MD...............
...............MD...............
................................
""",
    "BROCCOLI": """
...........HHH................
......HHHHHHAAAA..HHH.........
....HHHAHHHAAAAAHHHAAAA.......
...HHHAHHAAAAAAHHHAAAHHH......
..HHAAAHAAAAAAHHHHHHHHAAAA....
..HAAAAAAHHHADHHHAAAAAAAAAA...
...AAAAHHHAAAHHHAAAAAAAAAADA..
....AAHHHAAAHHAAAAAAADDAADDD..
.....HHAAAAAHAAAAAAADDDDDDD...
.....HAAAAAAAAAAAADDDDDDDD....
......AAAAADDDAAADDDDDDD......
.......AAADDDD..ADD...........
.........ADDHHGGDD............
............HHGGDD............
............HHGGDD............
............HHGGDD............
............HHGGDD............
.............HHDD.............
.............HHDD.............
.............HHDD.............
.............HHDD.............
.............HHDD.............
.............HHDD.............
.............HDDD.............
..............................
""",
    "TUBER": """
..............................
..............................
.........HHHHHHHHHH...........
......HHHHHHHHHHHHHHHH........
......HHHAAAADDDDDAHHHHGG.....
....HHDDDDDADDAAAAAAAAHDGGG...
...HHHAAAAAADDAAAAAAAAADGGG...
...HADDAAAAAAAAAAAAAAAADGGG...
..HAADDAADDDDDAAADDDDAADGGG...
.HHDAAAAADDDDDDDDDDDAAADGGG...
..HDDDDDDDDDDDDDDDDDDDADGGG...
....ADDDD..........ADDDDGGG...
......................ADGGG...
.........................GG...
..............................
..............................
""",
    "AVOCADO": """
............MMM...........
............MDD...........
............MDD...........
............MDD...........
...........MMHDA..........
...........MMHDD..........
..........MMHHDDA.........
..........MMHHDDD.........
.........MMHHADDDA........
........MMHHAAADDDA.......
.......MMHHAAAAADDDA......
......MMHHAAAAAAADDDA.....
.....MMHHAAAAAAAAADDDA....
....MMHHAAAHHHGDAAADDDA...
....MMHHAAHHHGGGDAADDDD...
...MMHHAAAGGGGGGDAAADDDA..
...MMHHAAAGGGGGGDAAADDDD..
...MMHHAAAGGGGGGDAAADDDD..
....MMHHAAADDDDDAAADDDD...
....MMHHAAAAAAAAAAADDDD...
.....MMHHAAAAAAAAADDDD....
.......MMDDDDDDDDDDD......
.........MMMMMMMDD........
...........MDDDD..........
..........................
""",
    "BOTTLE": """
.....HHMMMM.....
.....HMMMDD.....
......HAAD......
......HAAD......
......HAAD......
......HAAD......
......HAAD......
......HAAD......
......HAAD......
.....HAAAAA.....
....HAAAAAAA....
...HAAAAAAAAA...
..HAAAAAAAAAAA..
..HAAAAAAAAAAD..
..HAAAAAAAAAAD..
..HAAAAAAAAAAD..
..HDDDDDDDDDDD..
..HGGGGGGGGGGD..
..HGDDDDDDDDGD..
..HGGGGGGGGGGD..
..HGDDDDDDDDGD..
..HGGGGGGGGGGD..
..HDDDDDDDDDDD..
..HAAAAAAAAAAD..
..HAAAAAAAAAAD..
..HDDDDDDDDDDD..
""",
}

# label, index into a food row, unit, key into TARGETS
MACROS = [
    ["PROTEIN", 5, "G", "PROTEIN"],
    ["FAT", 6, "G", "FAT"],
    ["CARB", 7, "G", "CARB"],
    ["FIBRE", 8, "G", "FIBRE"],
]

MICROS = [
    ["B12", 9, "UG", "B12"],
    ["B6", 10, "MG", "B6"],
    ["ZINC", 11, "MG", "ZINC"],
    ["IRON", 12, "MG", "IRON"],
    ["SELENIUM", 13, "UG", "SELENIUM"],
    ["MAGNESIUM", 14, "MG", "MAGNESIUM"],
]

# ------------------------------------------------------------- text tools
def one(x):
    """One decimal place. The % operator here carries no width or precision
    flags, so this is done by hand."""
    v = int(x * 10 + 0.5)
    whole, frac = v // 10, v % 10
    return str(whole) + "." + str(frac)

def whole(x):
    return str(int(x + 0.5))

def clip(c, text, font, maxw):
    t = str(text)
    if c.text_width(t, font) <= maxw:
        return t
    for i in range(len(t), 0, -1):
        if c.text_width(t[:i], font) <= maxw:
            return t[:i]
    return ""

def fit(c, text, fonts, maxw):
    for f in fonts:
        if c.text_width(text, f) <= maxw:
            return [f, text]
    last = fonts[len(fonts) - 1]
    return [last, clip(c, text, last, maxw)]

def pick(c, options, font, maxw):
    """The first whole option that fits, so a label never loses its ending."""
    for t in options:
        if c.text_width(t, font) <= maxw:
            return t
    return ""

def rail(c, col):
    c.rect(0, 0, 1, 31, fill = col)

def pill(c, text, col, x, y):
    w = c.text_width(text, "4x5") + 4
    c.rect(x, y, x + w - 1, y + 6, fill = col)
    c.text(text, x + 2, y + 1, font = "4x5", color = "black")
    return w

# ------------------------------------------------------------------ pick
def rows_for(view, f):
    """The four rows page one shows.

    Macronutrients are the four macros in their usual order. Micronutrients
    are the four this food delivers most of, ranked, because the question
    the app answers is which foods get you to a goal - a fixed four would
    bury the reason oysters or liver are worth knowing about."""
    if view == "MICRONUTRIENTS":
        scored = []
        for m in MICROS:
            share = f[m[1]] / TARGETS[m[3]]
            scored.append([share, m])
        for i in range(1, len(scored)):
            k = i
            for _step in range(i):
                if k > 0 and scored[k][0] > scored[k - 1][0]:
                    scored[k], scored[k - 1] = scored[k - 1], scored[k]
                    k -= 1
        return [s[1] for s in scored[:4]]
    return MACROS

def choose(ctx):
    view = str(ctx.inputs.get("view", "MACRONUTRIENTS")).strip().upper()
    if view not in ["MACRONUTRIENTS", "MICRONUTRIENTS"]:
        view = "MACRONUTRIENTS"
    group = str(ctx.inputs.get("group", "ALL FOODS")).strip().upper()
    pool = []
    for f in FOODS:
        if group != "ALL FOODS" and f[1] != group:
            continue
        pool.append(f)
    if len(pool) == 0:
        return [view, group, None]
    # A new food every ten minutes, on the same beat the panel refreshes.
    return [view, group, pool[(ctx.now.unix // 600) % len(pool)]]

def empty(c, group):
    """Kept as a guard. Every group currently holds foods, so this is not
    reachable; it is written positive rather than as a fault."""
    c.fill("black")
    rail(c, MET)
    c.text("NO FOODS IN " + group, 96, 9, font = "6x8", color = MET,
           align = "center")
    c.text("TRY ANOTHER FOOD GROUP", 96, 20, font = "4x5", color = DIM,
           align = "center")

def draw_food(c, f):
    pal = PALETTES.get(f[3], PALETTES["white"])
    art = SPRITES.get(f[2], "")
    if art == "":
        return
    c.sprite(art, 10, 3, legend = {
        "H": pal[0], "M": pal[1], "D": pal[2], "A": pal[3], "G": pal[4],
    })

# ------------------------------------------------------------ page: food
def food(c, ctx):
    view, group, f = choose(ctx)
    if f == None:
        empty(c, group)
        return
    pal = PALETTES.get(f[3], PALETTES["white"])
    accent = pal[3]
    c.fill("black")
    rail(c, accent)

    draw_food(c, f)

    # The text column starts clear of the 44 px art box at x 10..53.
    # The header names the serving the rows are for, as "1 OZ 28G" where it
    # fits beside the name and the label alone where it does not. There is
    # room for the serving or for energy beside CHICKEN DRUMSTICK, not both,
    # so energy is on the detail page instead.
    tx = 58
    grams, label = serving(f)
    gl = whole(grams) + "G"
    right = pick(c, [label + " " + gl, label, gl], "4x5",
                 117 - c.text_width(f[0], "4x5"))
    if right == "":
        right = gl
    rw = c.text_width(right, "4x5")
    c.text(right, 181, 1, font = "4x5", color = DIM, align = "right")
    nm = clip(c, f[0], "4x5", 181 - rw - 3 - tx - 3)
    pill(c, nm, accent, tx, 0)

    # Four rows on a 6 px pitch. The right side is measured first, then the
    # bar takes what is left between the label column and the value.
    rows = rows_for(view, f)
    for i in range(len(rows)):
        r = rows[i]
        y = 8 + i * 6
        amount = per(f, r[1])
        target = TARGETS[r[3]]
        pctv = int(amount / target * 100 + 0.5)

        # "12.6G 13%" where it fits, the amount alone where it does not.
        # A whole-number form buys back room when both the amount and the
        # share are wide, as in 592.0MG 158% for pumpkin seed magnesium.
        val = pick(c, [one(amount) + r[2] + " " + str(pctv) + "%",
                       whole(amount) + r[2] + " " + str(pctv) + "%",
                       one(amount) + r[2], str(pctv) + "%"], "4x5", 52)
        vw = c.text_width(val, "4x5")
        c.text(val, 181, y, font = "4x5",
               color = MET if pctv >= 100 else INK, align = "right")

        # MAGNESIUM is the longest label in either view and was clipping to
        # MAGNESIU at 42 px, so the label column is 46 and the bar starts
        # four pixels later to pay for it.
        c.text(clip(c, r[0], "4x5", 46), tx, y, font = "4x5", color = DIM)

        bx0, bx1 = tx + 48, 181 - vw - 4
        if bx1 - bx0 >= 8:
            c.rect(bx0, y + 1, bx1, y + 3, fill = TRACK)
            fillw = (bx1 - bx0) * (pctv if pctv < 100 else 100) // 100
            if fillw > 0:
                c.rect(bx0, y + 1, bx0 + fillw, y + 3,
                       fill = MET if pctv >= 100 else accent)

# ---------------------------------------------------------- page: detail
def detail(c, ctx):
    view, group, f = choose(ctx)
    if f == None:
        empty(c, group)
        return
    pal = PALETTES.get(f[3], PALETTES["white"])
    accent = pal[3]
    c.fill("black")
    rail(c, accent)

    nm = clip(c, f[0], "4x5", 92)
    pill(c, nm, accent, 10, 0)

    # The serving again, in place of the food group. The macro view carries
    # energy in its grid; the micro view has no cell for it, so it rides
    # in the header there.
    grams, label = serving(f)
    gl = whole(grams) + "G"
    kcal = whole(per(f, 4)) + " KCAL"
    if view == "MICRONUTRIENTS":
        opts = [label + " " + gl + " " + kcal, label + " " + kcal,
                gl + " " + kcal]
    else:
        opts = [label + " " + gl, label, gl]
    basis = pick(c, opts, "4x5", 164 - c.text_width(nm, "4x5"))
    if basis == "":
        basis = opts[len(opts) - 1]
    c.text(basis, 181, 1, font = "4x5", color = DIM, align = "right")

    # Six cells, two columns by three rows. Macro view spends its sixth on
    # the micronutrient this food is actually notable for, which ties the
    # two views together.
    cells = []
    if view == "MICRONUTRIENTS":
        for m in MICROS:
            pctv = int(per(f, m[1]) / TARGETS[m[3]] * 100 + 0.5)
            cells.append([m[0], one(per(f, m[1])) + m[2], pctv])
    else:
        cells.append(["ENERGY", whole(per(f, 4)) + "KCAL", -1])
        for m in MACROS:
            pctv = int(per(f, m[1]) / TARGETS[m[3]] * 100 + 0.5)
            cells.append([m[0], one(per(f, m[1])) + m[2], pctv])
        best, bestpct = MICROS[0], -1
        for m in MICROS:
            p = int(per(f, m[1]) / TARGETS[m[3]] * 100 + 0.5)
            if p > bestpct:
                best, bestpct = m, p
        # The nutrient name lives in the value, because "BEST MAGNESIUM" as
        # a label clipped to BEST MAGNESIU. With the name moved, the label
        # itself then clipped to BES on almonds: "MAGNESIUM 72%" leaves 17 px
        # in an 81 px cell and BEST measures 19. TOP measures 14 and fits.
        cells.append(["TOP", best[0] + " " + str(bestpct) + "%", bestpct])

    for i in range(len(cells)):
        cell = cells[i]
        cx = 10 if i % 2 == 0 else 100
        cw = 84 if i % 2 == 0 else 81
        y = 9 + (i // 2) * 7
        vw = c.text_width(cell[1], "4x5")
        c.text(cell[1], cx + cw, y, font = "4x5",
               color = MET if cell[2] >= 100 else INK, align = "right")
        c.text(clip(c, cell[0], "4x5", cw - vw - 3), cx, y, font = "4x5",
               color = DIM)
